# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusionImg2ImgPipeline
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_QwenEditSkin(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        # device and multi_gpu are handled in the 'to' method for pipelines

        base_model_id = "Qwen/Qwen-Image-Edit-2509"
        lora_model_id = "tlennon-ie/qwen-edit-skin"

        # Load the base pipeline
        self.pipeline = StableDiffusionImg2ImgPipeline.from_pretrained(
            base_model_id,
            torch_dtype=torch.float16
        )

        # Load the LoRA weights into the pipeline
        self.pipeline.load_lora_weights(lora_model_id)

    def preprocess(self, input_images_and_prompts):
        images = []
        prompts = []
        for img_path, prompt in input_images_and_prompts:
            images.append(Image.open(img_path).convert('RGB'))
            prompts.append(prompt)
        
        # The pipeline expects the 'image' parameter for the input images
        return {"image": images, "prompt": prompts}

    def predict(self, model_input):
        # The model card suggests a trigger phrase
        # The prompt is expected to be something like "make the subjects skin details more prominent and natural"
        # Additional parameters like strength can be passed via config if needed
        strength = self.config.get("strength", 0.8)
        guidance_scale = self.config.get("guidance_scale", 7.5)
        
        return self.pipeline(
            **model_input, 
            strength=strength, 
            guidance_scale=guidance_scale
        ).images

    def postprocess(self, model_output):
        # The pipeline returns a list of PIL images
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.pipeline.to(device)

    def eval(self):
        # Pipelines manage their own state, this method is for compatibility
        pass

