# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import LayoutLMv2Processor, LayoutLMv2ForQuestionAnswering
from PIL import Image
import torch

class PyTorch_Transformers_LayoutLMv2_frizwankhan_entity_linking_model_final(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "frizwankhan/entity-linking-model-final"
        self.processor = LayoutLMv2Processor.from_pretrained(model_id)
        self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id)
        self.model.to(device)
        self.device = device

    def preprocess(self, input_document_images_and_questions):
        images, questions = [], []
        for input_image, question in input_document_images_and_questions:
            images.append(Image.open(input_image).convert('RGB'))
            questions.append(question)
        
        encoding = self.processor(images, questions, return_tensors="pt").to(self.device)
        self.encoding = encoding  # Store for postprocessing
        return encoding

    def predict(self, model_input):
        with torch.no_grad():
            outputs = self.model(**model_input)
        return outputs

    def postprocess(self, model_output):
        input_ids = self.encoding.input_ids
        start_logits = model_output.start_logits
        end_logits = model_output.end_logits

        answers = []
        for i in range(len(start_logits)):
            start_index = torch.argmax(start_logits[i])
            end_index = torch.argmax(end_logits[i])

            answer_ids = input_ids[i][start_index : end_index + 1]
            answer = self.processor.tokenizer.decode(answer_ids).strip()
            answers.append(answer)
        
        return answers
