# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import LayoutLMv2Processor, LayoutLMv2ForQuestionAnswering
from PIL import Image
import torch

class PyTorch_Transformers_PrimWong_layoutlm_qa(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "PrimWong/layoutlm_qa"
        self.processor = LayoutLMv2Processor.from_pretrained(model_id)
        self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id)

        self.device = torch.device(device)
        self.model.to(self.device)

    def preprocess(self, input_document_images_and_questions):
        images, questions = [], []
        for input_image, question in input_document_images_and_questions:
            images.append(Image.open(input_image).convert('RGB'))
            questions.append(question)

        encoding = self.processor(images, questions, return_tensors="pt", padding="max_length", truncation=True)
        return encoding

    def predict(self, model_input):
        model_input = {k: v.to(self.device) for k, v in model_input.items()}
        with torch.no_grad():
            outputs = self.model(**model_input)
        return (outputs, model_input)

    def postprocess(self, model_output):
        model_output, model_input = model_output_and_input
        input_ids = model_input["input_ids"]
        start_logits = model_output.start_logits
        end_logits = model_output.end_logits

        answers = []
        for i in range(len(start_logits)):
            answer_start_index = start_logits[i].argmax()
            answer_end_index = end_logits[i].argmax()
            
            predict_answer_tokens = input_ids[i, answer_start_index : answer_end_index + 1]
            answer = self.processor.tokenizer.decode(predict_answer_tokens, skip_special_tokens=True)
            answers.append(answer)

        return answers
