# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch

class PyTorch_Transformers_TinyCLIP_ViT_8M_16_Text_3M_YFCC15M(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M"
        
        self.processor = CLIPProcessor.from_pretrained(model_id)
        self.model = self.load_hf_model(CLIPModel, model_id)
        self.model.eval()

    def preprocess(self, input_images):
        # For CLIP models, preprocessing is handled in the predict step as it requires both images and text prompts.
        # This method will just load the images into PIL format.
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        return processed_images

    def predict(self, model_input):
        # model_input is a list of PIL images from preprocess
        # class_names is a list of strings (e.g., ['cat', 'dog'])
        text_prompts = [f"a photo of a {c}" for c in class_names]
        
        inputs = self.processor(text=text_prompts, images=model_input, return_tensors="pt", padding=True)
        inputs = self.to_device(inputs)
        
        return self.model(**inputs)

    def postprocess(self, model_output):
        # The model output contains logits_per_image, which are the image-text similarity scores.
        probabilities = torch.nn.functional.softmax(model_output.logits_per_image, dim=1)
        return probabilities.tolist()
