# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from PIL import Image
from open_clip import create_model_from_pretrained, get_tokenizer

class PyTorch_OpenClip_ViT_L_16_SigLIP2_512(PyTorchAbstractClass):
    def __init__(self, config=None):
        model_id = "hf-hub:timm/ViT-L-16-SigLIP2-512"
        self.model, self.preprocessor = create_model_from_pretrained(model_id)
        self.tokenizer = get_tokenizer(model_id)
        self.model.eval()

        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)

        # Pre-compute text features for ImageNet classes for zero-shot classification
        imagenet_prompts = [f"a photo of a {label}" for label in self.features]
        tokenized_text = self.tokenizer(imagenet_prompts, context_length=self.model.context_length)

        with torch.no_grad():
            # These features will be on CPU by default and moved to the correct device in postprocess
            self.text_features = self.model.encode_text(tokenized_text, normalize=True)

    def preprocess(self, input_images):
        processed_images = [
            self.preprocessor(Image.open(image_path).convert('RGB'))
            for image_path in input_images
        ]
        model_input = torch.stack(processed_images)
        return model_input

    def predict(self, model_input):
        with torch.no_grad():
            image_features = self.model.encode_image(model_input, normalize=True)
        return image_features

    def postprocess(self, model_output):
        # model_output is image_features from the predict step
        # Move pre-computed text features to the same device as the image features
        text_features_on_device = self.text_features.to(model_output.device)
        
        with torch.no_grad():
            # SigLIP formula for calculating probabilities
            logits = model_output @ text_features_on_device.T * self.model.logit_scale.exp() + self.model.logit_bias
            probabilities = torch.sigmoid(logits)
            
        return probabilities.tolist()
