# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import AutoPipelineForInpainting, DEISMultistepScheduler
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_DreamshaperInpainting(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        # multi_gpu is not directly used by pipelines but kept for consistency
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Lykon/dreamshaper-8-inpainting"
        
        self.pipeline = AutoPipelineForInpainting.from_pretrained(
            model_id,
            torch_dtype=torch.float16,
            variant="fp16"
        )
        self.pipeline.scheduler = DEISMultistepScheduler.from_config(self.pipeline.scheduler.config)

        self.seed = self.config.get('seed', 33)
        self.num_inference_steps = self.config.get('num_inference_steps', 25)
        self.generator = None
        self.device = None

    def preprocess(self, input_data):
        # input_data is expected to be a dictionary with keys: 'image_path', 'mask_path', 'prompt'
        image = Image.open(input_data['image_path']).convert("RGB")
        mask_image = Image.open(input_data['mask_path']).convert("RGB")
        prompt = input_data['prompt']
        
        return {"prompt": prompt, "image": image, "mask_image": mask_image}

    def predict(self, model_input):
        if self.generator is None:
            self.generator = torch.Generator(device=self.device).manual_seed(self.seed)

        return self.pipeline(
            **model_input, 
            generator=self.generator, 
            num_inference_steps=self.num_inference_steps
        ).images

    def postprocess(self, model_output):
        # The pipeline returns a list of PIL images
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)
        # Re-initialize generator on the correct device
        self.generator = torch.Generator(device=device).manual_seed(self.seed)

    def eval(self):
        # Pipelines manage their own evaluation state
        pass

