# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import LayoutLMv2Processor, LayoutLMv2ForQuestionAnswering
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from PIL import Image
import torch

class PyTorch_Transformers_LayoutLMv2_Base_Uncased_Finetuned_DocVQA(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "sahil-everlign/layoutlmv2-base-uncased_finetuned_docvqa_on_1200"
        self.processor = LayoutLMv2Processor.from_pretrained(model_id)
        self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id)
        self.model.to(device)
        self.device = device

    def preprocess(self, input_document_images_and_questions):
        images, questions = [], []
        for input_image, question in input_document_images_and_questions:
            images.append(Image.open(input_image).convert("RGB"))
            questions.append(question)

        encoding = self.processor(images, questions, return_tensors="pt", padding="max_length", truncation=True)
        return {k: v.to(self.device) for k, v in encoding.items()}

    def predict(self, model_input):
        with torch.no_grad():
            outputs = self.model(**model_input)
        return outputs, model_input['input_ids']

    def postprocess(self, model_output):
        outputs, input_ids = model_output
        start_logits = outputs.start_logits
        end_logits = outputs.end_logits

        start_indices = torch.argmax(start_logits, dim=1)
        end_indices = torch.argmax(end_logits, dim=1)

        answers = []
        for i in range(len(start_indices)):
            start_idx = start_indices[i].item()
            end_idx = end_indices[i].item()
            answer_ids = input_ids[i][start_idx : end_idx + 1]
            answer = self.processor.tokenizer.decode(answer_ids, skip_special_tokens=True)
            answers.append(answer.strip())

        return answers
