# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForImageClassification
from PIL import Image
import torch

class PyTorch_Transformers_ViT_Base_Patch16_224(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        model_id = "google/vit-base-patch16-224"
        
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        self.model = AutoModelForImageClassification.from_pretrained(model_id)
        self.model.eval()

        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        with torch.no_grad():
            outputs = self.model(**model_input)
        return outputs

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
