# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import LayoutLMv2Processor, LayoutLMv2ForQuestionAnswering
from PIL import Image
import torch

class PyTorch_Transformers_LayoutLMv2_Oksana76B_DocVQA(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        self.device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Oksana76B/document-question-answering"
        self.processor = LayoutLMv2Processor.from_pretrained(model_id)
        
        if multi_gpu and self.device == "cuda":
            self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id)
            self.model.to(self.device)

    def preprocess(self, input_document_images_and_questions):
        images, questions = [], []
        for image_path, question in input_document_images_and_questions:
            images.append(Image.open(image_path).convert("RGB"))
            questions.append(question)
        
        encoding = self.processor(images, questions, return_tensors="pt", padding="max_length", truncation=True)
        self.preprocessed_encoding = encoding
        return {k: v.to(self.device) for k, v in encoding.items()}

    def predict(self, model_input):
        with torch.no_grad():
            outputs = self.model(**model_input)
        return outputs.start_logits, outputs.end_logits

    def postprocess(self, model_output):
        start_logits, end_logits = model_output
        answers = []
        input_ids = self.preprocessed_encoding.input_ids

        for i in range(len(start_logits)):
            start_index = torch.argmax(start_logits[i])
            end_index = torch.argmax(end_logits[i])
            
            if start_index > end_index:
                answers.append("")
                continue
                
            answer_ids = input_ids[i][start_index : end_index + 1]
            answer = self.processor.tokenizer.decode(answer_ids, skip_special_tokens=True)
            answers.append(answer.strip())
            
        return answers
