# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
from PIL import Image

class PyTorch_Transformers_TrOCR_Large_Stage1(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        self.processor = TrOCRProcessor.from_pretrained("microsoft/trocr-large-stage1")
        
        if multi_gpu and device == "cuda":
            self.model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-large-stage1", device_map="auto", torch_dtype="auto")
        else:
            self.model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-large-stage1")
        
        self.max_length = self.config.get('max_length', 16)
        self.num_beams = self.config.get('num_beams', 4)

    def preprocess(self, input_images):
        images = []
        for image_path in input_images:
            images.append(Image.open(image_path).convert('RGB'))
        model_input = self.processor(images=images, return_tensors="pt").pixel_values
        return model_input

    def predict(self, model_input):
        return self.model.generate(model_input, max_length=self.max_length, num_beams=self.num_beams)

    def postprocess(self, model_output):
        preds = self.processor.batch_decode(model_output, skip_special_tokens=True)
        return [pred.strip() for pred in preds]
