# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import AutoPipelineForImage2Image
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_Qwen_Image_Edit_Relight(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        base_model_id = "Qwen/Qwen-Image-Edit-2509"
        lora_model_id = "dx8152/Qwen-Image-Edit-2509-Relight"

        self.pipeline = AutoPipelineForImage2Image.from_pretrained(
            base_model_id,
            torch_dtype=torch.float16,
            variant="fp16"
        )
        self.pipeline.load_lora_weights(lora_model_id)
        self.generator = torch.Generator(device="cpu").manual_seed(self.config.get("seed", 0))

    def preprocess(self, input_images_and_prompts):
        images = []
        prompts = []
        for img_path, prompt in input_images_and_prompts:
            images.append(Image.open(img_path).convert("RGB"))
            prompts.append(prompt)
        return {"image": images, "prompt": prompts}

    def predict(self, model_input):
        return self.pipeline(**model_input, generator=self.generator).images

    def postprocess(self, model_output):
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)
        self.generator = torch.Generator(device=device).manual_seed(self.config.get("seed", 0))

    def eval(self):
        pass
