# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoProcessor, VideoMAEForVideoClassification
import av
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_OpenGVLab_VideoMAEv2_giant(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "OpenGVLab/VideoMAEv2-giant"
        # This model requires trust_remote_code=True
        self.processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
        
        # Per instructions, use VideoMAEForVideoClassification for VideoMAE models.
        # trust_remote_code=True is required for the model configuration.
        # ignore_mismatched_sizes=True allows loading the base model weights into the classification architecture,
        # initializing a new classification head.
        if multi_gpu and device == "cuda":
            self.model = VideoMAEForVideoClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto", trust_remote_code=True, ignore_mismatched_sizes=True)
        else:
            self.model = VideoMAEForVideoClassification.from_pretrained(model_id, trust_remote_code=True, ignore_mismatched_sizes=True)

        # This base model is not fine-tuned for classification and lacks an id2label mapping.
        # We handle this gracefully by providing an empty list for features.
        if hasattr(self.model.config, 'id2label') and self.model.config.id2label:
            self.features = [v for k, v in sorted(self.model.config.id2label.items())]
        else:
            self.features = []

    def preprocess(self, input_videos):
        # These helper methods are assumed to be part of the base class or context
        def sample_frame_indices(clip_len, frame_sample_rate, seg_len):
            converted_len = int(clip_len * frame_sample_rate)
            end_idx = np.random.randint(converted_len, seg_len)
            start_idx = end_idx - converted_len
            indices = np.linspace(start_idx, end_idx, num=clip_len)
            indices = np.clip(indices, start_idx, end_idx - 1).astype(np.int64)
            return indices

        def read_video_pyav(container, indices):
            frames = []
            container.seek(0)
            for i, frame in enumerate(container.decode(video=0)):
                if i in indices:
                    frames.append(frame.to_ndarray(format="rgb24"))
            return np.stack(frames)

        container = av.open(input_videos[0])
        # Sample 16 frames, a common setting for video classification models
        indices = sample_frame_indices(clip_len=16, frame_sample_rate=1, seg_len=container.streams.video[0].frames)
        video = read_video_pyav(container, indices)
        
        # The processor expects a list of frames
        inputs = self.processor(videos=list(video), return_tensors="pt")
        
        # VideoMAEv2 models expect the channel dimension before the temporal dimension: (B, C, T, H, W)
        # The processor outputs (B, T, C, H, W), so we permute the dimensions accordingly.
        pixel_values = inputs['pixel_values'].permute(0, 2, 1, 3, 4)
        
        return pixel_values

    def predict(self, model_input):
        # The model expects the input tensor to be named 'pixel_values'
        return self.model(pixel_values=model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
