# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoTokenizer, AutoModelForTokenClassification

class PyTorch_Transformers_BERT_OncologyNER(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "OpenMed/OpenMed-NER-OncologyDetect-PubMed-335M"
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = AutoModelForTokenClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForTokenClassification.from_pretrained(model_id)

        self.features = list(self.model.config.id2label.values())

    def preprocess(self, input_texts):
        return self.tokenizer(input_texts, return_tensors="pt", padding=True, truncation=True)

    def predict(self, model_input):
        return self.model(**model_input).logits

    def postprocess(self, model_output):
        predictions = torch.argmax(model_output, dim=2)
        predicted_labels = [[self.features[p.item()] for p in prediction] for prediction in predictions]
        return predicted_labels
