# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Custom_StableNormal(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        # The model card specifies loading from a different repo via torch.hub,
        # using the yoso_version parameter to specify the actual model weights.
        hub_repo = "hugoycj/StableNormal"
        model_name_in_hub = "StableNormal_turbo"
        model_version = "Stable-X/yoso-normal-v1-8-1"

        self.model = torch.hub.load(
            hub_repo,
            model_name_in_hub,
            trust_repo=True,
            yoso_version=model_version
        )

    def preprocess(self, input_images):
        return [Image.open(img_path).convert('RGB') for img_path in input_images]

    def predict(self, model_input):
        # The model processes one image at a time
        return [self.model(image) for image in model_input]

    def postprocess(self, model_output):
        # The model output is a list of PIL Images, which need to be converted to numpy arrays and then lists for JSON serialization.
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.model.to(device)

    def eval(self):
        self.model.eval()
