import os
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field
from langchain_core.output_parsers import JsonOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI


def video_classification_model_automation(models_to_add=None):
    if models_to_add is None:
        return "No models specified for addition."

    MODEL_TEMPLATE = """# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

{imports}

class {class_name}(PyTorchAbstractClass):
    def __init__(self{init_config}):
        {init_body}

    def preprocess(self, input_videos):
        {preprocess_body}

    def predict(self, model_input):
        {predict_body}

    def postprocess(self, model_output):
        {postprocess_body}
"""

    class ModelConfig(BaseModel):
        """Configuration details for a PyTorch video classification model."""

        imports: str = Field(
            description="The complete imports section. Include torch, transformers (AutoProcessor, model classes), av for video reading, numpy. Use proper formatting with newlines.",
            default="import torch\nfrom transformers import AutoProcessor, VideoMAEForVideoClassification\nimport av\nimport numpy as np",
        )

        class_name: str = Field(
            description="The class name for the model. Should be descriptive and follow PascalCase convention, e.g., 'PyTorch_Transformers_XCLIP_Base'.",
        )

        init_config: str = Field(
            description="The __init__ method signature parameters. Typically ', config=None'.",
            default=", config=None",
        )

        init_body: str = Field(
            description="The complete body of the __init__ method. Should include: 1) config initialization, 2) loading processor and model from_pretrained, 3) extracting label features from model config. Include proper indentation (8 spaces).",
        )

        preprocess_body: str = Field(
            description="The complete body of the preprocess method. Should: 1) Read video with av, 2) Sample frames, 3) Process with processor, 4) Return pixel_values. Include proper indentation (8 spaces).",
        )

        predict_body: str = Field(
            description="The complete body of the predict method. Should call model and return logits. Include proper indentation (8 spaces).",
        )

        postprocess_body: str = Field(
            description="The complete body of the postprocess method. Should apply softmax and convert to list. Include proper indentation (8 spaces).",
        )

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                f"""
You are an expert in PyTorch video classification models. Your task is to generate a complete, working model.py file.

**IMPORTANT GUIDELINES:**

1. **Model Type Detection:**
   - VideoMAE models: Use VideoMAEForVideoClassification
   - X-CLIP models: Use similar architecture
   - All need frame sampling from videos

2. **Imports:**
   - Always include: `from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass`
   - Standard: `import torch`, `from transformers import AutoProcessor, VideoMAEForVideoClassification`
   - For video reading: `import av`, `import numpy as np`

3. **Init Method:**
   - Initialize config: `self.config = config if config else dict()`
   - **ALWAYS extract device and multi_gpu settings:**
     ```
     device = self.config.pop("_device", "cpu")
     multi_gpu = self.config.pop("_multi_gpu", False)
     ```
   - Load processor from_pretrained
   - **Load model with multi-GPU support:**
     ```
     if multi_gpu and device == "cuda":
         self.model = VideoMAEForVideoClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
     else:
         self.model = VideoMAEForVideoClassification.from_pretrained(model_id)
     ```
   - Extract labels: `self.features = [v for k, v in sorted(self.model.config.text_config['id2label'].items())]` or similar

4. **Preprocess Method:**
   - Read video with av.open
   - Sample frames (typically 16 frames)
   - Process with processor: `self.processor(videos=frames, return_tensors="pt").pixel_values`

5. **Predict Method:**
   - Call model: `return self.model(model_input)`

6. **Postprocess Method:**
   - Apply softmax: `torch.nn.functional.softmax(model_output.logits, dim=1).tolist()`

**Reference Example:**

{{{{
    "imports": "import torch\\nfrom transformers import AutoProcessor, VideoMAEForVideoClassification\\nimport av\\nimport numpy as np",
    "class_name": "PyTorch_Transformers_XCLIP_Base_Patch32",
    "init_config": ", config=None",
    "init_body": "self.config = config if config else dict()\\n        device = self.config.pop(\\"_device\\", \\"cpu\\")\\n        multi_gpu = self.config.pop(\\"_multi_gpu\\", False)\\n\\n        model_id = \\"microsoft/xclip-base-patch32\\"\\n        self.processor = AutoProcessor.from_pretrained(model_id)\\n        \\n        if multi_gpu and device == \\"cuda\\":\\n            self.model = VideoMAEForVideoClassification.from_pretrained(model_id, device_map=\\"auto\\", torch_dtype=\\"auto\\")\\n        else:\\n            self.model = VideoMAEForVideoClassification.from_pretrained(model_id)\\n\\n        self.features = [v for k, v in sorted(self.model.config.text_config['id2label'].items())]",
    "preprocess_body": "container = av.open(input_videos[0])\\n        indices = self.sample_frame_indices(clip_len=16, frame_sample_rate=1, seg_len=container.streams.video[0].frames)\\n        video = self.read_video_pyav(container, indices)\\n        pixel_values = self.processor(videos=list(video), return_tensors=\\"pt\\").pixel_values\\n        return pixel_values",
    "predict_body": "return self.model(model_input)",
    "postprocess_body": "probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)\\n        return probabilities.tolist()"
}}}}

Respond ONLY with the JSON structure matching the ModelConfig schema.
""",
            ),
            (
                "human",
                """
Context from Hugging Face page:
---
{model_page_context}
---
Generate config for model: '{model_identifier}'

Use the exact model identifier '{model_identifier}' in the init_body.
""",
            ),
        ]
    )

    modelCounter = 0
    load_dotenv()
    if not os.getenv("GOOGLE_API_KEY"):
        raise EnvironmentError("GOOGLE_API_KEY not found.")

    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-pro",
        model_kwargs={"thinkingBudget": -1},
        temperature=0,
        convert_system_message_to_human=True,
    )
    parser = JsonOutputParser(pydantic_object=ModelConfig)
    chain = prompt | llm | parser

    BASE_DIR = "mlmodelscope/pytorch_agent/models/default/video_classification"
    ERROR_DIR = f"{BASE_DIR}/errors"
    os.makedirs(ERROR_DIR, exist_ok=True)
    failed_models = []
    login_req_models = []

    for model_name in models_to_add:
        if modelCounter == 50:
            break
        print(f"\n--- Processing model: {model_name} ---")

        model_folder_name = (
            model_name.split("/")[-1].replace("-", "_").replace(".", "_").lower()
        )
        model_py_path = os.path.join(BASE_DIR, model_folder_name, "model.py")

        if os.path.exists(model_py_path):
            print(f"Model '{model_folder_name}' already exists. Skipping.")
            continue

        error_log = ""
        try:
            check_syntax = lambda fn: os.system(f"python -m py_compile {fn}")
            error = False
            while not os.path.exists(model_py_path) or (
                error := check_syntax(model_py_path)
            ):
                if error:
                    error_log += f"Syntax error, regenerating...\n"

                url = f"https://huggingface.co/{model_name}"
                response = requests.get(url)
                response.raise_for_status()

                soup = BeautifulSoup(response.text, "html.parser")
                main_content = (
                    soup.find("model-card-content")
                    or soup.find("main")
                    or soup.find("body")
                )

                if not main_content:
                    break

                login_link = main_content.find(
                    "a", href=lambda h: h and h.startswith("/login?next=")
                )
                if login_link:
                    login_req_models.append(model_name)
                    break

                context_text = main_content.get_text(separator=" ", strip=True)
                if len(context_text) > 20000:
                    context_text = context_text[:20000] + "\n... (truncated)"

                model_config_dict = chain.invoke(
                    {
                        "model_identifier": model_name,
                        "model_page_context": context_text,
                    }
                )

                init_body = model_config_dict.get("init_body", "").replace(
                    "{hugging_face_model_id}", model_name
                )

                filled_template = MODEL_TEMPLATE.format(
                    imports=model_config_dict.get(
                        "imports",
                        "import torch\nfrom transformers import AutoProcessor, VideoMAEForVideoClassification\nimport av\nimport numpy as np",
                    ),
                    class_name=model_config_dict.get(
                        "class_name", "PyTorch_Video_Classification_Model"
                    ),
                    init_config=model_config_dict.get("init_config", ", config=None"),
                    init_body=init_body.lstrip(" "),
                    preprocess_body=model_config_dict.get(
                        "preprocess_body", "pass"
                    ).lstrip(" "),
                    predict_body=model_config_dict.get(
                        "predict_body", "return self.model(model_input)"
                    ).lstrip(" "),
                    postprocess_body=model_config_dict.get(
                        "postprocess_body",
                        "return torch.nn.functional.softmax(model_output.logits, dim=1).tolist()",
                    ).lstrip(" "),
                )

                model_dir = os.path.join(BASE_DIR, model_folder_name)
                os.makedirs(model_dir, exist_ok=True)

                with open(model_py_path, "w") as f:
                    f.write(filled_template)

            else:
                print(f"Successfully generated {model_py_path}")
                modelCounter += 1

        except Exception as e:
            print(f"Failed: {e}")
            import traceback

            traceback.print_exc()
            failed_models.append(model_name)

    print(f"\n--- Automation complete ---")
    with open(os.path.join(ERROR_DIR, "failed_models.log"), "w") as f:
        for fm in failed_models:
            f.write(f"{fm}\n")
    with open(os.path.join(ERROR_DIR, "login_req_models.log"), "w") as f:
        for lm in login_req_models:
            f.write(f"{lm}\n")


if __name__ == "__main__":
    video_classification_model_automation(
        models_to_add=["microsoft/xclip-base-patch32"]
    )

