# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
import torchvision.transforms as T
from torchvision.transforms.functional import InterpolationMode
from PIL import Image
from transformers import AutoModel, AutoTokenizer
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

def build_transform(input_size):
    MEAN, STD = IMAGENET_MEAN, IMAGENET_STD
    transform = T.Compose([
        T.Lambda(lambda img: img.convert('RGB') if img.mode != 'RGB' else img),
        T.Resize((input_size, input_size), interpolation=InterpolationMode.BICUBIC),
        T.ToTensor(),
        T.Normalize(mean=MEAN, std=STD)
    ])
    return transform

def find_closest_aspect_ratio(aspect_ratio, target_ratios, width, height, image_size):
    best_ratio_diff = float('inf')
    best_ratio = (1, 1)
    area = width * height
    for ratio in target_ratios:
        target_aspect_ratio = ratio[0] / ratio[1]
        ratio_diff = abs(aspect_ratio - target_aspect_ratio)
        if ratio_diff < best_ratio_diff:
            best_ratio_diff = ratio_diff
            best_ratio = ratio
        elif ratio_diff == best_ratio_diff:
            if area > 0.5 * image_size * image_size * ratio[0] * ratio[1]:
                best_ratio = ratio
    return best_ratio

def dynamic_preprocess(image, min_num=1, max_num=12, image_size=448, use_thumbnail=False):
    orig_width, orig_height = image.size
    aspect_ratio = orig_width / orig_height
    target_ratios = set(
        (i, j) for n in range(min_num, max_num + 1) for i in range(1, n + 1) for j in range(1, n + 1) if
        i * j <= max_num and i * j >= min_num)
    target_ratios = sorted(target_ratios, key=lambda x: x[0] * x[1])
    target_aspect_ratio = find_closest_aspect_ratio(
        aspect_ratio, target_ratios, orig_width, orig_height, image_size)
    target_width = image_size * target_aspect_ratio[0]
    target_height = image_size * target_aspect_ratio[1]
    blocks = target_aspect_ratio[0] * target_aspect_ratio[1]
    resized_img = image.resize((target_width, target_height))
    processed_images = []
    for i in range(blocks):
        box = (
            (i % (target_width // image_size)) * image_size,
            (i // (target_width // image_size)) * image_size,
            ((i % (target_width // image_size)) + 1) * image_size,
            ((i // (target_width // image_size)) + 1) * image_size
        )
        split_img = resized_img.crop(box)
        processed_images.append(split_img)
    assert len(processed_images) == blocks
    if use_thumbnail and len(processed_images) != 1:
        thumbnail_img = image.resize((image_size, image_size))
        processed_images.append(thumbnail_img)
    return processed_images

class PyTorch_Transformers_InternVL2_2B(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "OpenGVLab/InternVL2-2B"
        self.model = self.load_hf_model(
            AutoModel,
            model_id,
            trust_remote_code=True,
            torch_dtype=torch.bfloat16
        )
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_id,
            trust_remote_code=True,
            use_fast=False
        )
        self.max_new_tokens = self.config.get('max_new_tokens', 1024)
        self.generation_config = dict(max_new_tokens=self.max_new_tokens, do_sample=True)

    def preprocess(self, input_image_and_questions):
        all_pixel_values = []
        num_patches_list = []
        questions = []

        for image_path, question in input_image_and_questions:
            pixel_values = self._load_image(image_path)
            all_pixel_values.append(pixel_values)
            num_patches_list.append(pixel_values.shape[0])
            questions.append(f'<image>\n{question}')

        pixel_values_cat = torch.cat(all_pixel_values, dim=0).to(torch.bfloat16)

        return {
            'pixel_values': pixel_values_cat,
            'num_patches_list': num_patches_list,
            'questions': questions
        }

    def predict(self, model_input):
        return self.model.batch_chat(
            tokenizer=self.tokenizer,
            pixel_values=model_input['pixel_values'],
            num_patches_list=model_input['num_patches_list'],
            questions=model_input['questions'],
            generation_config=self.generation_config
        )

    def postprocess(self, model_output):
        return model_output
