# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusionXLPipeline, EulerAncestralDiscreteScheduler, AutoencoderKL

class PyTorch_Diffusers_Animagine_XL_3_0(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        torch_dtype = torch.float16 if multi_gpu and device == "cuda" else torch.float32

        vae = AutoencoderKL.from_pretrained(
            "madebyollin/sdxl-vae-fp16-fix",
            torch_dtype=torch_dtype
        )
        
        self.pipeline = StableDiffusionXLPipeline.from_pretrained(
            "cagliostrolab/animagine-xl-3.0",
            vae=vae,
            torch_dtype=torch_dtype,
            use_safetensors=True,
        )
        self.pipeline.scheduler = EulerAncestralDiscreteScheduler.from_config(self.pipeline.scheduler.config)

        self.negative_prompt = self.config.get('negative_prompt', "nsfw, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name")
        self.width = self.config.get('width', 832)
        self.height = self.config.get('height', 1216)
        self.guidance_scale = self.config.get('guidance_scale', 7)
        self.num_inference_steps = self.config.get('num_inference_steps', 28)

    def preprocess(self, input_prompts):
        return input_prompts

    def predict(self, model_input):
        return self.pipeline(
            prompt=model_input, 
            negative_prompt=self.negative_prompt, 
            width=self.width,
            height=self.height,
            guidance_scale=self.guidance_scale,
            num_inference_steps=self.num_inference_steps
        ).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
