# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import PaliGemmaProcessor, PaliGemmaForConditionalGeneration
from PIL import Image

class PyTorch_Transformers_NayanaVQA(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Nayana-cognitivelab/NayanaVQA"
        self.processor = PaliGemmaProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = PaliGemmaForConditionalGeneration.from_pretrained(model_id, device_map="auto", torch_dtype=torch.bfloat16)
        else:
            self.model = PaliGemmaForConditionalGeneration.from_pretrained(model_id, torch_dtype=torch.bfloat16)

        self.max_new_tokens = self.config.get('max_new_tokens', 100)

    def preprocess(self, input_image_and_questions):
        images = [Image.open(item[0]).convert('RGB') for item in input_image_and_questions]
        questions = [item[1] for item in input_image_and_questions]

        messages_list = []
        for question in questions:
            messages = [
                {"role": "user", "content": f"<image>\n{question}"}
            ]
            messages_list.append(messages)

        prompts = [self.processor.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True) for messages in messages_list]
        
        return self.processor(text=prompts, images=images, return_tensors="pt", padding=True)

    def predict(self, model_input):
        return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        decoded_outputs = self.processor.batch_decode(model_output, skip_special_tokens=True)
        return [output.split('<|start_header_id|>assistant<|end_header_id|>')[1].strip() for output in decoded_outputs]
