# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import FluxControlNetModel, FluxControlNetPipeline
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_FluxControlNetUpscaler(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "jasperai/Flux.1-dev-Controlnet-Upscaler"
        base_model_id = "black-forest-labs/FLUX.1-dev"

        torch_dtype = torch.bfloat16 if device == "cuda" and torch.cuda.is_available() and torch.cuda.is_bf16_supported() else torch.float32

        controlnet = FluxControlNetModel.from_pretrained(model_id, torch_dtype=torch_dtype)

        self.pipeline = FluxControlNetPipeline.from_pretrained(
            base_model_id,
            controlnet=controlnet,
            torch_dtype=torch_dtype
        )

        self.upscale_factor = self.config.get("upscale_factor", 4)
        self.controlnet_conditioning_scale = self.config.get("controlnet_conditioning_scale", 0.6)
        self.num_inference_steps = self.config.get("num_inference_steps", 28)
        self.guidance_scale = self.config.get("guidance_scale", 3.5)

    def preprocess(self, input_images):
        # This implementation processes one image at a time.
        # The runner is expected to iterate through the list of images.
        if not input_images:
            raise ValueError("Input image list cannot be empty.")

        img_path = input_images[0]
        image = Image.open(img_path).convert("RGB")
        w, h = image.size
        target_w, target_h = int(w * self.upscale_factor), int(h * self.upscale_factor)

        # Resize the low-res image to the target size to be used as the control image
        control_image = image.resize((target_w, target_h), Image.Resampling.LANCZOS)

        # The prompt is typically empty for this upscaler but can be configured
        prompt = self.config.get("prompt", "")

        return {
            "prompt": prompt,
            "control_image": control_image,
            "height": target_h,
            "width": target_w,
            "controlnet_conditioning_scale": self.controlnet_conditioning_scale,
            "num_inference_steps": self.num_inference_steps,
            "guidance_scale": self.guidance_scale
        }

    def predict(self, model_input):
        return self.pipeline(**model_input).images

    def postprocess(self, model_output):
        # The pipeline returns a list of PIL images
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        # Pipelines manage their own state, this method is for interface consistency
        pass

