import os
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field
from langchain_core.output_parsers import JsonOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI


def document_visual_question_answering_model_automation(models_to_add=None):
    if models_to_add is None:
        return "No models specified for addition."

    MODEL_TEMPLATE = """# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

{imports}

class {class_name}(PyTorchAbstractClass):
    def __init__(self{init_config}):
        {init_body}

    def preprocess(self, input_document_images_and_questions):
        {preprocess_body}

    def predict(self, model_input):
        {predict_body}

    def postprocess(self, model_output):
        {postprocess_body}
"""

    class ModelConfig(BaseModel):
        """Configuration details for a PyTorch document VQA model."""

        imports: str = Field(
            description="The complete imports section. Include transformers (DonutProcessor, VisionEncoderDecoderModel or similar), PIL Image, re for parsing. Use proper formatting with newlines.",
            default="from transformers import DonutProcessor, VisionEncoderDecoderModel\nfrom PIL import Image\nimport re",
        )

        class_name: str = Field(
            description="The class name for the model. Should be descriptive and follow PascalCase convention, e.g., 'PyTorch_Transformers_Donut_DocVQA'.",
        )

        init_config: str = Field(
            description="The __init__ method signature parameters. Typically ', config=None'.",
            default=", config=None",
        )

        init_body: str = Field(
            description="The complete body of the __init__ method. Should include: 1) config initialization, 2) loading processor and model from_pretrained. Include proper indentation (8 spaces).",
        )

        preprocess_body: str = Field(
            description="The complete body of the preprocess method. Receives list of (image_path, question) tuples. Should: 1) Load images with PIL, 2) Format questions with task prompts, 3) Process with processor. Include proper indentation (8 spaces).",
        )

        predict_body: str = Field(
            description="The complete body of the predict method. Should call model.generate with appropriate parameters. Include proper indentation (8 spaces).",
        )

        postprocess_body: str = Field(
            description="The complete body of the postprocess method. Should decode sequences, parse answers with regex, extract answer field. Include proper indentation (8 spaces).",
        )

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                f"""
You are an expert in PyTorch document VQA models. Your task is to generate a complete, working model.py file.

**IMPORTANT GUIDELINES:**

1. **Model Type Detection:**
   - Donut models: Use DonutProcessor + VisionEncoderDecoderModel
   - LayoutLM variants: Different architecture
   - Most document VQA models use vision-encoder-decoder

2. **Imports:**
   - Always include: `from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass`
   - For Donut: `from transformers import DonutProcessor, VisionEncoderDecoderModel`, `from PIL import Image`, `import re`

3. **Init Method:**
   - Load processor and model from_pretrained

4. **Preprocess Method:**
   - Input: list of (image_path, question) tuples
   - Load images, format questions with task-specific prompts
   - For Donut DocVQA: `f"<s_docvqa><s_question>{{question}}</s_question><s_answer>"`
   - Process with processor

5. **Predict Method:**
   - Generate with model: `self.model.generate(model_input['pixel_values'], decoder_input_ids=model_input['labels'], ...)`

6. **Postprocess Method:**
   - Decode sequences
   - Parse with regex to extract answers
   - Return list of answers

**Reference Example:**

{{{{
    "imports": "from transformers import DonutProcessor, VisionEncoderDecoderModel\\nfrom PIL import Image\\nimport re",
    "class_name": "PyTorch_Transformers_Donut_Base_finetuned_DocVQA",
    "init_config": ", config=None",
    "init_body": "self.config = config if config else dict()\\n        model_id = \\"naver-clova-ix/donut-base-finetuned-docvqa\\"\\n        self.processor = DonutProcessor.from_pretrained(model_id)\\n        self.model = VisionEncoderDecoderModel.from_pretrained(model_id)",
    "preprocess_body": "images, questions = [], []\\n        for input_image, question in input_document_images_and_questions:\\n            images.append(Image.open(input_image).convert('RGB'))\\n            questions.append(f\\"<s_docvqa><s_question>{{question}}</s_question><s_answer>\\")\\n        return self.processor(images=images, text=questions, add_special_tokens=False, padding=True, return_tensors=\\"pt\\")",
    "predict_body": "return self.model.generate(model_input['pixel_values'], decoder_input_ids=model_input['labels'], max_length=self.model.decoder.config.max_position_embeddings, pad_token_id=self.processor.tokenizer.pad_token_id, eos_token_id=self.processor.tokenizer.eos_token_id, use_cache=True, bad_words_ids=[[self.processor.tokenizer.unk_token_id]], return_dict_in_generate=True)",
    "postprocess_body": "sequences = self.processor.batch_decode(model_output.sequences)\\n        answers = []\\n        for sequence in sequences:\\n            sequence = sequence.replace(self.processor.tokenizer.eos_token, \\"\\").replace(self.processor.tokenizer.pad_token, \\"\\")\\n            sequence = re.sub(r\\"<.*?>\\", \\"\\", sequence, count=1).strip()\\n            answer = self.processor.token2json(sequence)['answer']\\n            answers.append(answer)\\n        return answers"
}}}}

Respond ONLY with the JSON structure matching the ModelConfig schema.
""",
            ),
            (
                "human",
                """
Context from Hugging Face page:
---
{model_page_context}
---
Generate config for model: '{model_identifier}'

Use the exact model identifier '{model_identifier}' in the init_body.
""",
            ),
        ]
    )

    modelCounter = 0
    load_dotenv()
    if not os.getenv("GOOGLE_API_KEY"):
        raise EnvironmentError("GOOGLE_API_KEY not found.")

    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-pro",
        model_kwargs={"thinkingBudget": -1},
        temperature=0,
        convert_system_message_to_human=True,
    )
    parser = JsonOutputParser(pydantic_object=ModelConfig)
    chain = prompt | llm | parser

    BASE_DIR = "mlmodelscope/pytorch_agent/models/default/document_visual_question_answering"
    ERROR_DIR = f"{BASE_DIR}/errors"
    os.makedirs(ERROR_DIR, exist_ok=True)
    failed_models = []
    login_req_models = []

    for model_name in models_to_add:
        if modelCounter == 50:
            break
        print(f"\n--- Processing model: {model_name} ---")

        model_folder_name = (
            model_name.split("/")[-1].replace("-", "_").replace(".", "_").lower()
        )
        model_py_path = os.path.join(BASE_DIR, model_folder_name, "model.py")

        if os.path.exists(model_py_path):
            print(f"Model '{model_folder_name}' already exists. Skipping.")
            continue

        error_log = ""
        try:
            check_syntax = lambda fn: os.system(f"python -m py_compile {fn}")
            error = False
            while not os.path.exists(model_py_path) or (
                error := check_syntax(model_py_path)
            ):
                if error:
                    error_log += f"Syntax error, regenerating...\n"

                url = f"https://huggingface.co/{model_name}"
                response = requests.get(url)
                response.raise_for_status()

                soup = BeautifulSoup(response.text, "html.parser")
                main_content = (
                    soup.find("model-card-content")
                    or soup.find("main")
                    or soup.find("body")
                )

                if not main_content:
                    break

                login_link = main_content.find(
                    "a", href=lambda h: h and h.startswith("/login?next=")
                )
                if login_link:
                    login_req_models.append(model_name)
                    break

                context_text = main_content.get_text(separator=" ", strip=True)
                if len(context_text) > 20000:
                    context_text = context_text[:20000] + "\n... (truncated)"

                model_config_dict = chain.invoke(
                    {
                        "model_identifier": model_name,
                        "model_page_context": context_text,
                    }
                )

                init_body = model_config_dict.get("init_body", "").replace(
                    "{hugging_face_model_id}", model_name
                )

                filled_template = MODEL_TEMPLATE.format(
                    imports=model_config_dict.get(
                        "imports",
                        "from transformers import DonutProcessor, VisionEncoderDecoderModel\nfrom PIL import Image\nimport re",
                    ),
                    class_name=model_config_dict.get(
                        "class_name", "PyTorch_Document_VQA_Model"
                    ),
                    init_config=model_config_dict.get("init_config", ", config=None"),
                    init_body=init_body.lstrip(" "),
                    preprocess_body=model_config_dict.get(
                        "preprocess_body", "pass"
                    ).lstrip(" "),
                    predict_body=model_config_dict.get(
                        "predict_body", "return self.model.generate(**model_input)"
                    ).lstrip(" "),
                    postprocess_body=model_config_dict.get(
                        "postprocess_body",
                        "return self.processor.batch_decode(model_output, skip_special_tokens=True)",
                    ).lstrip(" "),
                )

                model_dir = os.path.join(BASE_DIR, model_folder_name)
                os.makedirs(model_dir, exist_ok=True)

                with open(model_py_path, "w") as f:
                    f.write(filled_template)

            else:
                print(f"Successfully generated {model_py_path}")
                modelCounter += 1

        except Exception as e:
            print(f"Failed: {e}")
            import traceback

            traceback.print_exc()
            failed_models.append(model_name)

    print(f"\n--- Automation complete ---")
    with open(os.path.join(ERROR_DIR, "failed_models.log"), "w") as f:
        for fm in failed_models:
            f.write(f"{fm}\n")
    with open(os.path.join(ERROR_DIR, "login_req_models.log"), "w") as f:
        for lm in login_req_models:
            f.write(f"{lm}\n")


if __name__ == "__main__":
    document_visual_question_answering_model_automation(
        models_to_add=["naver-clova-ix/donut-base-finetuned-docvqa"]
    )

