# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
import torch
from transformers import AutoModelForCausalLM
from PIL import Image

class PyTorch_Transformers_OneAlign(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "q-future/one-align"
        
        # This model requires specific arguments for loading as per the model card
        self.model = AutoModelForCausalLM.from_pretrained(
            model_id,
            trust_remote_code=True,
            attn_implementation="eager",
            torch_dtype=torch.float16,
            device_map="auto"
        )
        self.model.eval()

    def preprocess(self, input_images):
        # The model's custom score function takes a list of PIL images directly
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        return processed_images

    def predict(self, model_input):
        # This model uses a custom 'score' method instead of the standard forward pass
        # The task is hardcoded to 'quality' as shown in the model card's quick start example
        # The output is expected to be a tensor of scores
        with torch.no_grad():
            scores = self.model.score(model_input, task_="quality", input_="image")
        return scores

    def postprocess(self, model_output):
        # The model outputs a raw score for quality, not a probability distribution.
        # We need to format this into the expected list-of-lists structure.
        if isinstance(model_output, torch.Tensor):
            scores_list = model_output.cpu().tolist()
        else:
            scores_list = model_output

        # Ensure it's a list for consistent processing
        if not isinstance(scores_list, list):
            scores_list = [scores_list]

        # Each score is the single 'class' or output for an image
        return [[score] for score in scores_list]
