# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
import torch

class PyTorch_Transformers_Kaleidoscope_small_v1(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        self.device = device

        model_id = "2KKLabs/Kaleidoscope_small_v1"
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForQuestionAnswering.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForQuestionAnswering.from_pretrained(model_id)
            self.model.to(self.device)

    def preprocess(self, input_document_images_and_questions):
        questions = []
        contexts = []
        for document_path, question in input_document_images_and_questions:
            with open(document_path, "r", encoding="utf-8") as f:
                context = f.read()
            questions.append(question)
            contexts.append(context)
        
        inputs = self.tokenizer(questions, contexts, return_tensors="pt", padding=True, truncation=True, max_length=512)
        return {k: v.to(self.device) for k, v in inputs.items()}

    def predict(self, model_input):
        outputs = self.model(**model_input)
        return {"outputs": outputs, "inputs": model_input}

    def postprocess(self, model_output):
        outputs = model_output["outputs"]
        inputs = model_output["inputs"]
        
        start_logits = outputs.start_logits
        end_logits = outputs.end_logits
        input_ids = inputs["input_ids"]
        
        answers = []
        for i in range(len(input_ids)):
            start_index = torch.argmax(start_logits[i])
            end_index = torch.argmax(end_logits[i])
            
            # Ensure the start_index is not after the end_index
            if start_index > end_index:
                answer_tokens = []
            else:
                answer_tokens = input_ids[i][start_index : end_index + 1]
            
            answer = self.tokenizer.decode(answer_tokens, skip_special_tokens=True)
            answers.append(answer.strip())
            
        return answers
