# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoModelForCausalLM, AutoProcessor
import librosa
import torch

class PyTorch_Transformers_Phi4_Multimodal_Instruct(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "microsoft/Phi-4-multimodal-instruct"

        self.processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
        self.prompt_template = "<|user|><|audio_1|>Transcribe the audio clip into text.<|end|><|assistant|>"

        if multi_gpu and device == "cuda":
            self.model = AutoModelForCausalLM.from_pretrained(
                model_id, 
                device_map="auto", 
                torch_dtype="auto", 
                trust_remote_code=True
            )
        else:
            self.model = AutoModelForCausalLM.from_pretrained(
                model_id, 
                trust_remote_code=True
            )

        self.sampling_rate = self.config.get('sampling_rate', 16_000)

    def preprocess(self, input_audios):
        audios = []
        for audio_path in input_audios:
            audio_array, _ = librosa.load(audio_path, sr=self.sampling_rate)
            audios.append((audio_array, self.sampling_rate))
        
        prompts = [self.prompt_template] * len(audios)
        
        model_input = self.processor(
            text=prompts, 
            audios=audios, 
            return_tensors="pt",
            padding=True
        )
        return model_input

    def predict(self, model_input):
        input_ids = model_input['input_ids']
        # From the model card example, max_new_tokens=1000 is used.
        generate_ids = self.model.generate(**model_input, max_new_tokens=1000)
        # The model's output includes the prompt, so we slice it off to return only the generated part.
        generated_tokens_only = generate_ids[:, input_ids.shape[1]:]
        return generated_tokens_only

    def postprocess(self, model_output):
        # The model card example specifies these decoding options.
        return self.processor.batch_decode(
            model_output, 
            skip_special_tokens=True, 
            clean_up_tokenization_spaces=False
        )
