# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, SiglipForImageClassification
from PIL import Image
import torch

class PyTorch_Transformers_OpenDeepfakeDetection(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        
        model_id = "prithivMLmods/open-deepfake-detection"
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = SiglipForImageClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = SiglipForImageClassification.from_pretrained(model_id)
        
        self.model.eval()

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        with torch.no_grad():
            outputs = self.model(**model_input)
        return outputs

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
