# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForImageClassification
from PIL import Image
import torch

class PyTorch_Timm_Eva02_Large_Patch14_Clip_224(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "timm/eva02_large_patch14_clip_224.merged2b_s4b_b131k"
        
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        self.model = self.load_hf_model(AutoModelForImageClassification, model_id)
        self.model.eval()

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
