# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoModel, AutoProcessor
from PIL import Image
import torch

class PyTorch_Transformers_MarqoFashionCLIP(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Marqo/marqo-fashionCLIP"
        self.processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

        if multi_gpu and device == "cuda":
            self.model = AutoModel.from_pretrained(model_id, trust_remote_code=True, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModel.from_pretrained(model_id, trust_remote_code=True).to(device)
        
        self.model.eval()

        # For zero-shot classification, labels must be provided to compute text features
        self.labels = self.config.get("labels", [])
        self.text_features = None
        if self.labels:
            text_inputs = self.processor(text=self.labels, padding='max_length', return_tensors="pt")
            # Move text inputs to the same device as the model
            text_inputs = {k: v.to(self.model.device) for k, v in text_inputs.items()}
            with torch.no_grad():
                self.text_features = self.model.get_text_features(**text_inputs, normalize=True)

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        pixel_values = model_input['pixel_values'].to(self.model.device)
        with torch.no_grad():
            # This model's prediction step is to generate image embeddings (features)
            image_features = self.model.get_image_features(pixel_values=pixel_values, normalize=True)
        return image_features

    def postprocess(self, model_output):
        if self.text_features is None or self.text_features.shape[0] == 0:
            raise ValueError("Labels were not provided during initialization for this zero-shot model.")

        # model_output from predict() is the image_features tensor
        # Calculate similarity between image features and pre-computed text features
        logits_per_image = 100.0 * model_output @ self.text_features.T
        probabilities = logits_per_image.softmax(dim=-1)
        return probabilities.cpu().tolist()
