# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_GroundingDinoBase(PyTorchAbstractClass):
    def __init__(self):
        super().__init__(config)
        model_id = "tictag-io-demo/grounding-dino-base"
        self.processor = AutoProcessor.from_pretrained(model_id)
        self.load_hf_model(AutoModelForZeroShotObjectDetection, model_id)

    def preprocess(self, input_images):
        images = []
        target_sizes = []
        for img_path in input_images:
            image = Image.open(img_path).convert("RGB")
            images.append(image)
            target_sizes.append(image.size[::-1])

        if "text_queries" not in kwargs:
            raise ValueError("This model requires 'text_queries' (a list of strings) in kwargs.")
        
        text = " . ".join(kwargs["text_queries"]) + " ."
        model_input = self.processor(images=images, text=text, return_tensors="pt")

        self._target_sizes = torch.tensor(target_sizes)
        self._input_ids = model_input.input_ids

        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        results = self.processor.post_process_grounded_object_detection(
            model_output,
            self._input_ids,
            box_threshold=0.4,
            text_threshold=0.3,
            target_sizes=self._target_sizes
        )

        result = results[0]
        scores = result['scores'].tolist()
        labels = result['labels']
        boxes = result['boxes'].tolist()

        return [scores], [labels], [boxes]
