# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForSemanticSegmentation
from PIL import Image
import torch

class PyTorch_Transformers_Mask2Former_Swin_Large_Mapillary_Vistas_Semantic(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "facebook/mask2former-swin-large-mapillary-vistas-semantic"

        self.processor = AutoImageProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = AutoModelForSemanticSegmentation.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForSemanticSegmentation.from_pretrained(model_id)
            self.model.to(device)

    def preprocess(self, input_images):
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        class_queries_logits = model_output.class_queries_logits
        masks_queries_logits = model_output.masks_queries_logits
        # Reconstruct the semantic map from the queries
        semantic_segmentation = torch.einsum("bqc, bqhw -> bchw", class_queries_logits.softmax(-1), masks_queries_logits.sigmoid())
        # Get the final prediction by taking the argmax
        predicted_map = torch.argmax(semantic_segmentation, dim=1)
        return predicted_map.tolist()
