# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import ViltProcessor, ViltForQuestionAnswering
from PIL import Image

class PyTorch_Transformers_ViLT_b32_finetuned_vqa(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "dandelin/vilt-b32-finetuned-vqa"
        self.processor = ViltProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = ViltForQuestionAnswering.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = ViltForQuestionAnswering.from_pretrained(model_id)

    def preprocess(self, input_image_and_questions):
        images = [Image.open(input_image_and_question[0]).convert('RGB') for input_image_and_question in input_image_and_questions]
        questions = [input_image_and_question[1] for input_image_and_question in input_image_and_questions]
        return self.processor(images, questions, return_tensors="pt", padding=True, truncation=True)

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        logits = model_output.logits
        predicted_ids = logits.argmax(-1)
        return [self.model.config.id2label[idx.item()] for idx in predicted_ids]
