# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import LayoutLMv2Processor, LayoutLMv2ForQuestionAnswering
from PIL import Image
import torch

class PyTorch_Transformers_CIVQA_Impira_QA_EasyOCR(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Sharka/CIVQA_Impira_QA_EasyOCR"
        self.processor = LayoutLMv2Processor.from_pretrained(model_id)
        self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id)

    def preprocess(self, input_document_images_and_questions):
        images, questions = [], []
        for image_path, question in input_document_images_and_questions:
            images.append(Image.open(image_path).convert("RGB"))
            questions.append(question)
        
        encoding = self.processor(images, questions, return_tensors="pt", padding="max_length", truncation=True)
        return encoding

    def predict(self, model_input):
        outputs = self.model(**model_input)
        
        start_indices = torch.argmax(outputs.start_logits, dim=1)
        end_indices = torch.argmax(outputs.end_logits, dim=1)
        
        input_ids = model_input["input_ids"]
        
        answers = []
        for i in range(len(start_indices)):
            start_idx = start_indices[i]
            end_idx = end_indices[i]
            
            if start_idx > end_idx:
                answers.append("")
                continue

            answer_span = input_ids[i][start_idx : end_idx + 1]
            answer = self.processor.tokenizer.decode(answer_span, skip_special_tokens=True)
            answers.append(answer)
            
        return answers

    def postprocess(self, model_output):
        return model_output
