# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
import torch
from transformers import PaliGemmaProcessor, PaliGemmaForConditionalGeneration
from PIL import Image

class PyTorch_Transformers_Gemma_3n_E4B_IT_MLX_8bit(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "google/gemma-3n-E4B-it"
        self.processor = PaliGemmaProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = PaliGemmaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.bfloat16,
                device_map="auto",
                revision="bfloat16"
            ).eval()
        else:
            self.model = PaliGemmaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.bfloat16,
                revision="bfloat16"
            ).eval()

        self.max_new_tokens = self.config.get('max_new_tokens', 100)
        self.questions = []

    def preprocess(self, input_image_and_questions):
        images = [Image.open(item[0]).convert('RGB') for item in input_image_and_questions]
        self.questions = [item[1] for item in input_image_and_questions]
        return self.processor(text=self.questions, images=images, return_tensors="pt", padding=True)

    def predict(self, model_input):
        return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        full_outputs = self.processor.batch_decode(model_output, skip_special_tokens=True)
        cleaned_answers = []
        for question, full_output in zip(self.questions, full_outputs):
            if full_output.startswith(question):
                answer = full_output[len(question):].lstrip()
                cleaned_answers.append(answer)
            else:
                cleaned_answers.append(full_output)
        return cleaned_answers
