# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, DFineForObjectDetection
from PIL import Image
import torch
import warnings

class PyTorch_Transformers_DFineSmallCoco(PyTorchAbstractClass):
    def __init__(self, config, model_id: str = "ustc-community/dfine-small-coco"):
        super().__init__(config)
        warnings.warn("The batch size should be 1.")
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        self.model = self.load_hf_model(DFineForObjectDetection, model_id)

    def preprocess(self, input_images):
        images = [Image.open(p).convert("RGB") for p in input_images]
        self.original_sizes = [img.size[::-1] for img in images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor(self.original_sizes)
        results = self.processor.post_process_object_detection(model_output, target_sizes=target_sizes)
        return [results[0]['scores'].tolist()], [results[0]['labels'].tolist()], [results[0]['boxes'].tolist()]