# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusionXLControlNetPipeline, ControlNetModel
from controlnet_aux import OpenposeDetector
from PIL import Image

class PyTorch_Diffusers_ControlNet_OpenPose_SDXL_V1_0(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        self.openpose = OpenposeDetector.from_pretrained("lllyasviel/ControlNet")

        dtype = torch.float16 if multi_gpu and device == "cuda" else torch.float32
        
        controlnet = ControlNetModel.from_pretrained(
            "thibaud/controlnet-openpose-sdxl-1.0",
            torch_dtype=dtype
        )
        self.pipeline = StableDiffusionXLControlNetPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-base-1.0",
            controlnet=controlnet,
            torch_dtype=dtype
        )
        self.num_inference_steps = self.config.get('num_inference_steps', 25)

    def preprocess(self, input_prompts):
        # input_data is a list of dicts, each with 'prompt' (string) and 'image' (PIL.Image)
        prompts = [item['prompt'] for item in input_data]
        conditioning_images_pil = [item['image'] for item in input_data]
        
        # Process images with OpenposeDetector
        processed_images = [self.openpose(img) for img in conditioning_images_pil]
        
        # The pipeline expects a list of prompts and a list of conditioning images
        return {"prompt": prompts, "image": processed_images}

    def predict(self, model_input):
        # model_input is a dict with "prompt" and "image" keys
        return self.pipeline(**model_input, num_inference_steps=self.num_inference_steps).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)
        self.openpose.to(device)

    def eval(self):
        pass
