# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, LlavaForConditionalGeneration
from PIL import Image
import torch
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_LLaVA_Image_Captioning(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "katuni4ka/tiny-random-llava"
        self.processor = AutoProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = LlavaForConditionalGeneration.from_pretrained(
                model_id,
                torch_dtype=torch.float16,
                device_map="auto"
            )
        else:
            self.model = LlavaForConditionalGeneration.from_pretrained(model_id).to(device)

        self.prompt = self.config.get('prompt', "USER: <image>\nWhat is in this image?\nASSISTANT:")
        self.max_new_tokens = self.config.get('max_new_tokens', 50)

    def preprocess(self, input_images):
        device = self.model.device
        images = [Image.open(image_path).convert('RGB') for image_path in input_images]
        model_input = self.processor(text=self.prompt, images=images, return_tensors="pt").to(device)
        return model_input

    def predict(self, model_input):
        # The model_input is a dictionary, so we unpack it
        input_ids_len = model_input["input_ids"].shape[1]
        
        # Generate the full sequence
        full_output = self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)
        
        # Slice the output to get only the newly generated tokens
        generated_ids = full_output[:, input_ids_len:]
        
        return generated_ids

    def postprocess(self, model_output):
        # The model_output now contains only the generated token IDs
        preds = self.processor.batch_decode(model_output, skip_special_tokens=True)
        return [pred.strip() for pred in preds]
