# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import LayoutLMForQuestionAnswering, AutoTokenizer
from PIL import Image
import pytesseract
from pytesseract import Output
import torch

class PyTorch_Transformers_Impira_Layoutlm_Document_Qa(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "impira/layoutlm-document-qa"
        
        # Use AutoTokenizer to correctly load the tokenizer for the model.
        # This model uses a RobertaTokenizer, and AutoTokenizer handles this automatically,
        # fixing the TypeError.
        # We also remove the incorrect LayoutLMv2Processor, as this is a LayoutLMv1 model.
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)
        
        self.model = self.load_hf_model(LayoutLMForQuestionAnswering, model_id)

    def preprocess(self, input_document_images_and_questions):
        questions, all_words, all_boxes = [], [], []
        # The input is a batch of samples. Each sample is a list containing dicts for image and question.
        for sample in input_document_images_and_questions:
            # Assuming the first element is the image and the second is the question
            # The dataloader likely pre-processes the input, removing the dictionary structure.
            # The error "TypeError: string indices must be integers" indicates that sample[0] is a string.
            input_image = sample[0]
            question = sample[1]
            
            image = Image.open(input_image).convert("RGB")
            questions.append(question)
            width, height = image.size
            ocr_data = pytesseract.image_to_data(image, output_type=Output.DICT)
            words, boxes = [], []
            for i in range(len(ocr_data['text'])):
                if ocr_data['text'][i].strip():
                    x, y, w, h = ocr_data['left'][i], ocr_data['top'][i], ocr_data['width'][i], ocr_data['height'][i]
                    normalized_box = [int(1000 * x / width), int(1000 * y / height), int(1000 * (x + w) / width), int(1000 * (y + h) / height)]
                    words.append(ocr_data['text'][i])
                    boxes.append(normalized_box)
            all_words.append(words)
            all_boxes.append(boxes)
        
        # For LayoutLMv1, we pass the question, words, and boxes directly to the tokenizer.
        # The incorrect LayoutLMv2Processor is not needed.
        return self.tokenizer(questions, all_words, boxes=all_boxes, return_tensors="pt", padding="max_length", truncation=True)

    def predict(self, model_input):
        outputs = self.model(**model_input)
        return {"start_logits": outputs.start_logits, "end_logits": outputs.end_logits, "input_ids": model_input.input_ids}

    def postprocess(self, model_output):
        start_logits = model_output["start_logits"]
        end_logits = model_output["end_logits"]
        input_ids = model_output["input_ids"]
        answers = []
        for i in range(len(start_logits)):
            start_index = torch.argmax(start_logits[i])
            end_index = torch.argmax(end_logits[i])
            answer_tokens = input_ids[i][start_index : end_index + 1]
            answer = self.tokenizer.decode(answer_tokens).strip()
            answers.append(answer)
        return answers