# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_DeformableDetr(PyTorchAbstractClass):
    def __init__(selfself, config):
        super().__init__(config)
        self.processor = AutoImageProcessor.from_pretrained('SenseTime/deformable-detr')
        self.model = self.load_hf_model(AutoModelForObjectDetection, 'SenseTime/deformable-detr')

    def preprocess(self, input_images):
        images = [Image.open(path).convert("RGB") for path in input_images]
        self.target_sizes = torch.tensor([img.size[::-1] for img in images])
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        results = self.processor.post_process_object_detection(model_output, target_sizes=self.target_sizes, threshold=0.0)[0]
        scores = results['scores'].tolist()
        labels = results['labels'].tolist()
        boxes = results['boxes'].tolist()
        return [scores], [labels], [boxes]
