import os
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field
from langchain_core.output_parsers import JsonOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI


def image_semantic_segmentation_model_automation(models_to_add=None):
    if models_to_add is None:
        return "No models specified for addition."

    MODEL_TEMPLATE = """# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

{imports}

class {class_name}(PyTorchAbstractClass):
    def __init__(self{init_config}):
        {init_body}

    def preprocess(self, input_images):
        {preprocess_body}

    def predict(self, model_input):
        {predict_body}

    def postprocess(self, model_output):
        {postprocess_body}
"""

    class ModelConfig(BaseModel):
        """Configuration details for a PyTorch semantic segmentation model."""

        imports: str = Field(
            description="The complete imports section. Include torch, torchvision segmentation models or transformers, PIL Image, warnings if needed. Use proper formatting with newlines.",
            default="import torch\nfrom torchvision.models.segmentation import deeplabv3_resnet50, DeepLabV3_ResNet50_Weights\nfrom PIL import Image\nimport warnings",
        )

        class_name: str = Field(
            description="The class name for the model. Should be descriptive and follow PascalCase convention, e.g., 'PyTorch_TorchVision_DeepLabV3_ResNet50'.",
        )

        init_config: str = Field(
            description="The __init__ method signature parameters. May be empty or ', config=None'.",
            default="",
        )

        init_body: str = Field(
            description="The complete body of the __init__ method. Should include: 1) loading model (for torchvision: use pretrained=True or weights parameter, for transformers: from_pretrained), 2) warning about batch size if needed. Include proper indentation (8 spaces).",
        )

        preprocess_body: str = Field(
            description="The complete body of the preprocess method. Should: 1) Get preprocessor/transforms, 2) Open images with PIL, convert to RGB, 3) Apply transforms, 4) Stack images into tensor. Include proper indentation (8 spaces).",
        )

        predict_body: str = Field(
            description="The complete body of the predict method. Should call model(model_input) and return predictions. Include proper indentation (8 spaces).",
        )

        postprocess_body: str = Field(
            description="The complete body of the postprocess method. Should extract segmentation masks using torch.argmax on 'out' key, convert to list. Include proper indentation (8 spaces).",
        )

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                f"""
You are an expert in PyTorch semantic segmentation models. Your task is to generate a complete, working model.py file.

**IMPORTANT GUIDELINES:**

1. **Model Type Detection:**
   - TorchVision models (DeepLabV3, FCN, etc.): Use torchvision.models.segmentation
   - Transformers models (SegFormer, Mask2Former, etc.): Use transformers library
   - Most common: DeepLabV3 variants

2. **Imports:**
   - Always include: `from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass`
   - For TorchVision: `import torch`, model function and Weights class, `from PIL import Image`, `import warnings`
   - For Transformers: `from transformers import AutoImageProcessor, AutoModelForSemanticSegmentation`, `from PIL import Image`

3. **Init Method:**
   - Initialize config: `self.config = config if config else dict()`
   - **ALWAYS extract device and multi_gpu settings:**
     ```
     device = self.config.pop("_device", "cpu")
     multi_gpu = self.config.pop("_multi_gpu", False)
     ```
   - For TorchVision: Load model with pretrained=True or weights parameter (doesn't support device_map)
   - Add warning: `warnings.warn("If the size of the images is not consistent, the batch size should be 1.")`
   - **For Transformers: Load processor and model with multi-GPU support:**
     ```
     if multi_gpu and device == "cuda":
         self.model = AutoModelForSemanticSegmentation.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
     else:
         self.model = AutoModelForSemanticSegmentation.from_pretrained(model_id)
     ```

4. **Preprocess Method:**
   - For TorchVision: Get transforms from Weights.DEFAULT.transforms(), open images, apply transforms, stack
   - For Transformers: Use processor with images, return_tensors="pt"

5. **Predict Method:**
   - Call: `return self.model(model_input)`

6. **Postprocess Method:**
   - For TorchVision: Extract 'out' from dict, apply argmax: `torch.argmax(model_output["out"], axis=1).tolist()`
   - For Transformers: May need to extract logits and apply argmax

**Reference Example:**

TorchVision DeepLabV3 (with config extraction)
{{{{
    "imports": "import torch\\nfrom torchvision.models.segmentation import deeplabv3_resnet50, DeepLabV3_ResNet50_Weights\\nfrom PIL import Image\\nimport warnings",
    "class_name": "PyTorch_TorchVision_DeepLabV3_ResNet50",
    "init_config": ", config=None",
    "init_body": "self.config = config if config else dict()\\n        device = self.config.pop(\\"_device\\", \\"cpu\\")\\n        multi_gpu = self.config.pop(\\"_multi_gpu\\", False)\\n\\n        warnings.warn(\\"If the size of the images is not consistent, the batch size should be 1.\\")\\n        # Note: TorchVision models don't support device_map\\n        self.model = deeplabv3_resnet50(pretrained=True)",
    "preprocess_body": "preprocessor = DeepLabV3_ResNet50_Weights.DEFAULT.transforms()\\n        for i in range(len(input_images)):\\n            input_images[i] = preprocessor(Image.open(input_images[i]).convert('RGB'))\\n        model_input = torch.stack(input_images)\\n        return model_input",
    "predict_body": "return self.model(model_input)",
    "postprocess_body": "return torch.argmax(model_output[\\"out\\"], axis=1).tolist()"
}}}}

Respond ONLY with the JSON structure matching the ModelConfig schema.
""",
            ),
            (
                "human",
                """
Context from Hugging Face page:
---
{model_page_context}
---
Generate config for model: '{model_identifier}'

Use the exact model identifier '{model_identifier}' in the init_body.
""",
            ),
        ]
    )

    modelCounter = 0
    load_dotenv()
    if not os.getenv("GOOGLE_API_KEY"):
        raise EnvironmentError("GOOGLE_API_KEY not found.")

    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-pro",
        model_kwargs={"thinkingBudget": -1},
        temperature=0,
        convert_system_message_to_human=True,
    )
    parser = JsonOutputParser(pydantic_object=ModelConfig)
    chain = prompt | llm | parser

    BASE_DIR = "mlmodelscope/pytorch_agent/models/default/image_semantic_segmentation"
    ERROR_DIR = f"{BASE_DIR}/errors"
    os.makedirs(ERROR_DIR, exist_ok=True)
    failed_models = []
    login_req_models = []

    for model_name in models_to_add:
        if modelCounter == 50:
            break
        print(f"\n--- Processing model: {model_name} ---")

        model_folder_name = (
            model_name.split("/")[-1].replace("-", "_").replace(".", "_").lower()
        )
        model_py_path = os.path.join(BASE_DIR, model_folder_name, "model.py")

        if os.path.exists(model_py_path):
            print(f"Model '{model_folder_name}' already exists. Skipping.")
            continue

        error_log = ""
        try:
            check_syntax = lambda fn: os.system(f"python -m py_compile {fn}")
            error = False
            MAX_TRIES_PER_MODEL = 5
            try_count_my_model = 0
            while not os.path.exists(model_py_path) or (
                error := check_syntax(model_py_path)
            ):
                if try_count_my_model >= MAX_TRIES_PER_MODEL:
                    break
                try_count_my_model += 1
                if error:
                    error_log += f"Syntax error, regenerating...\n"

                url = f"https://huggingface.co/{model_name}"
                response = requests.get(url)
                response.raise_for_status()

                soup = BeautifulSoup(response.text, "html.parser")
                main_content = (
                    soup.find("model-card-content")
                    or soup.find("main")
                    or soup.find("body")
                )

                if not main_content:
                    break

                login_link = main_content.find(
                    "a", href=lambda h: h and h.startswith("/login?next=")
                )
                if login_link:
                    login_req_models.append(model_name)
                    break

                context_text = main_content.get_text(separator=" ", strip=True)
                if len(context_text) > 20000:
                    context_text = context_text[:20000] + "\n... (truncated)"

                model_config_dict = chain.invoke(
                    {
                        "model_identifier": model_name,
                        "model_page_context": context_text,
                    }
                )

                init_body = model_config_dict.get("init_body", "").replace(
                    "{hugging_face_model_id}", model_name
                )

                filled_template = MODEL_TEMPLATE.format(
                    imports=model_config_dict.get(
                        "imports",
                        "import torch\nfrom torchvision.models.segmentation import deeplabv3_resnet50, DeepLabV3_ResNet50_Weights\nfrom PIL import Image\nimport warnings",
                    ),
                    class_name=model_config_dict.get(
                        "class_name", "PyTorch_Semantic_Segmentation_Model"
                    ),
                    init_config=model_config_dict.get("init_config", ""),
                    init_body=init_body.lstrip(" "),
                    preprocess_body=model_config_dict.get(
                        "preprocess_body", "pass"
                    ).lstrip(" "),
                    predict_body=model_config_dict.get(
                        "predict_body", "return self.model(model_input)"
                    ).lstrip(" "),
                    postprocess_body=model_config_dict.get(
                        "postprocess_body",
                        'return torch.argmax(model_output["out"], axis=1).tolist()',
                    ).lstrip(" "),
                )

                model_dir = os.path.join(BASE_DIR, model_folder_name)
                os.makedirs(model_dir, exist_ok=True)

                with open(model_py_path, "w") as f:
                    f.write(filled_template)

            else:
                print(f"Successfully generated {model_py_path}")
                modelCounter += 1

        except Exception as e:
            print(f"Failed: {e}")
            import traceback

            traceback.print_exc()
            failed_models.append(model_name)

    print(f"\n--- Automation complete ---")
    with open(os.path.join(ERROR_DIR, "failed_models.log"), "w") as f:
        for fm in failed_models:
            f.write(f"{fm}\n")
    with open(os.path.join(ERROR_DIR, "login_req_models.log"), "w") as f:
        for lm in login_req_models:
            f.write(f"{lm}\n")


if __name__ == "__main__":
    image_semantic_segmentation_model_automation(
        models_to_add=["nvidia/segformer-b0-finetuned-ade-512-512"]
    )
