# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoModelForCTC, AutoProcessor
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
import librosa

class PyTorch_Transformers_Parakeet_CTC_1_1b(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "nvidia/parakeet-ctc-1.1b"
        self.processor = AutoProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForCTC.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForCTC.from_pretrained(model_id)

        self.sampling_rate = self.config.get('sampling_rate', 16_000)

    def preprocess(self, input_audios):
        audio_arrays = []
        for audio_path in input_audios:
            audio_array, _ = librosa.load(audio_path, sr=self.sampling_rate)
            audio_arrays.append(audio_array)
        
        model_input = self.processor(audio_arrays, sampling_rate=self.sampling_rate, return_tensors="pt", padding="longest")
        return model_input

    def predict(self, model_input):
        return self.model.generate(**model_input)

    def postprocess(self, model_output):
        return self.processor.batch_decode(model_output, skip_special_tokens=True)
