# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoProcessor, VideoMAEForVideoClassification
import av
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_Videomae_Crime_Detector_Production_V1(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Nikeytas/videomae-crime-detector-production-v1"
        self.processor = AutoProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = VideoMAEForVideoClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = VideoMAEForVideoClassification.from_pretrained(model_id)

        self.features = [v for k, v in sorted(self.model.config.id2label.items())]

    def preprocess(self, input_videos):
        def read_video_pyav(container, indices):
            frames = []
            container.seek(0)
            indices_set = set(indices)
            frame_dict = {}
            for frame in container.decode(video=0):
                if frame.index in indices_set:
                    frame_dict[frame.index] = frame.to_ndarray(format="rgb24")
            
            ordered_frames = [frame_dict[idx] for idx in indices]
            return ordered_frames

        container = av.open(input_videos[0])
        total_frames = container.streams.video[0].frames
        num_frames_to_sample = 16
        indices = np.linspace(0, total_frames - 1, num=min(total_frames, num_frames_to_sample), dtype=int)

        video_frames = read_video_pyav(container, indices)
        
        pixel_values = self.processor(videos=video_frames, return_tensors="pt").pixel_values
        return pixel_values

    def predict(self, model_input):
        return self.model(model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
