# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, AutoModelForZeroShotImageClassification
from PIL import Image
import torch

class PyTorch_Transformers_CLIP_ConvNext_Base_W_Laion2B(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "laion/CLIP-convnext_base_w-laion2B-s13B-b82K-augreg"
        self.processor = AutoProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = AutoModelForZeroShotImageClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForZeroShotImageClassification.from_pretrained(model_id)
            self.model.to(device)

        self.model.eval()

        # Download and prepare ImageNet labels for zero-shot classification
        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)
        self.text_prompts = [f"a photo of a {label}" for label in self.features]
        self.text_inputs = self.processor(text=self.text_prompts, return_tensors="pt", padding=True)

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        # The model_input from preprocess contains pixel_values.
        # We combine it with the pre-computed text inputs for zero-shot classification.
        # The trainer/wrapper is expected to move the combined dictionary to the correct device.
        combined_input = {
            "pixel_values": model_input.pixel_values,
            "input_ids": self.text_inputs.input_ids.to(self.model.device),
            "attention_mask": self.text_inputs.attention_mask.to(self.model.device)
        }
        return self.model(**combined_input)

    def postprocess(self, model_output):
        # The model output contains logits which are the similarity scores between the image and each text prompt.
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
