# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
import open_clip
import torch
from PIL import Image

class PyTorch_Transformers_CLIP_ConvNext_Base_W_Laion2B(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        self.device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = 'hf-hub:laion/CLIP-convnext_base_w-laion2B-s13B-b82K-augreg'
        
        try:
             self.model, self.preprocessor = open_clip.create_model_from_pretrained(model_id)
        except Exception as e:
             raise ImportError(f"Failed to load OpenCLIP model: {e}")
             
        self.tokenizer = open_clip.get_tokenizer(model_id)

        self.model.to(self.device)
        self.model.eval()

        self.labels = self.config.get("labels")
        if not self.labels or not isinstance(self.labels, list):
             features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
             self.labels = self.features_download(features_file_url)
             
        # Pre-tokenize labels
        text_tokens = self.tokenizer(self.labels).to(self.device)
        
        with torch.no_grad():
             self.text_features = self.model.encode_text(text_tokens)
             self.text_features /= self.text_features.norm(dim=-1, keepdim=True)

    def to(self, device, multi_gpu=False):
        self.model.to(device)
        self.device = device

    def preprocess(self, input_images):
        processed_images = [
            self.preprocessor(Image.open(image_path).convert('RGB'))
            for image_path in input_images
        ]
        model_input = torch.stack(processed_images)
        return model_input

    def predict(self, model_input):
        model_input = model_input.to(self.device)
        
        with torch.no_grad():
            image_features = self.model.encode_image(model_input)
            image_features /= image_features.norm(dim=-1, keepdim=True)
            
            # Use the model's learned temperature parameter
            logit_scale = self.model.logit_scale.exp()
            
            # Calculate cosine similarity
            logits = logit_scale * image_features @ self.text_features.T
            
        return logits

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output, dim=1)
        return probabilities.tolist()
