# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import LayoutLMv2Processor, LayoutLMv2ForQuestionAnswering
from PIL import Image
import torch
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_AlinaKozyreva_LayoutLMv2(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "AlinaKozyreva/AlinaKozyreva"
        self.processor = LayoutLMv2Processor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id)

    def preprocess(self, input_document_images_and_questions):
        images = [Image.open(img_path).convert("RGB") for img_path, _ in input_document_images_and_questions]
        questions = [q for _, q in input_document_images_and_questions]
        return self.processor(images, questions, return_tensors="pt", padding="max_length", truncation=True)

    def predict(self, model_input):
        outputs = self.model(**model_input)
        return {"outputs": outputs, "input_ids": model_input["input_ids"]}

    def postprocess(self, model_output):
        outputs = model_output["outputs"]
        input_ids = model_output["input_ids"]

        start_indices = torch.argmax(outputs.start_logits, dim=1)
        end_indices = torch.argmax(outputs.end_logits, dim=1)

        answers = []
        for i in range(len(start_indices)):
            start_idx = start_indices[i]
            end_idx = end_indices[i]
            answer_ids = input_ids[i][start_idx : end_idx + 1]
            answer = self.processor.tokenizer.decode(answer_ids, skip_special_tokens=True)
            answers.append(answer.strip())

        return answers
