# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
import timm
from PIL import Image
from torchvision import transforms

class Timm_ViT_Base_Patch32_Clip_224_Laion400m(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = 'timm/vit_base_patch32_clip_224.laion400m_e32'
        self.model = timm.create_model(model_id, pretrained=True)
        self.model.to(device)

        if multi_gpu and device == "cuda":
            self.model = torch.nn.DataParallel(self.model)

        self.model.eval()

        data_config = timm.data.resolve_data_config({}, model=self.model)
        self.transform = timm.data.create_transform(**data_config)

    def preprocess(self, input_images):
        processed_images = [
            self.transform(Image.open(image_path).convert('RGB'))
            for image_path in input_images
        ]
        model_input = torch.stack(processed_images)
        return model_input

    def predict(self, model_input):
        return self.model(model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output, dim=1)
        return probabilities.tolist()
