# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import LuminaNextT2IPipeline

class PyTorch_Diffusers_NetaYume_Lumina_Image_2_0(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        if multi_gpu and device == "cuda":
            self.pipeline = LuminaNextT2IPipeline.from_pretrained("duongve/NetaYume-Lumina-Image-2.0", torch_dtype=torch.float16)
        else:
            self.pipeline = LuminaNextT2IPipeline.from_pretrained("duongve/NetaYume-Lumina-Image-2.0")
        self.num_inference_steps = self.config.get('num_inference_steps', 40)
        self.guidance_scale = self.config.get('guidance_scale', 5.0)

    def preprocess(self, input_prompts):
        return input_prompts

    def predict(self, model_input):
        return self.pipeline(prompt=model_input, num_inference_steps=self.num_inference_steps, guidance_scale=self.guidance_scale).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
