# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusionPipeline, AutoencoderKL

class PyTorch_Diffusers_StableDiffusion_VAE_Flax(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        torch_dtype = torch.float16 if multi_gpu and device == "cuda" else torch.float32

        vae = AutoencoderKL.from_pretrained(
            "enterprise-explorers/sd-vae-ft-mse-flax", 
            from_flax=True, 
            torch_dtype=torch_dtype
        )
        
        self.pipeline = StableDiffusionPipeline.from_pretrained(
            "runwayml/stable-diffusion-v1-5", 
            vae=vae, 
            torch_dtype=torch_dtype
        )
        self.num_inference_steps = self.config.get('num_inference_steps', 50)

    def preprocess(self, input_prompts):
        return input_prompts

    def predict(self, model_input):
        return self.pipeline(model_input, num_inference_steps=self.num_inference_steps).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
