# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoProcessor, AutoModelForCausalLM
from PIL import Image
import warnings

class PyTorch_Transformers_OpenGVLab_InternVL3_5_241B_A28B_Instruct(PyTorchAbstractClass):
    def __init__(self, config=None):
        warnings.warn("This is a very large model. Ensure you have enough VRAM. Batch processing with different image sizes may not be stable.")
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "OpenGVLab/InternVL3_5-241B-A28B-Instruct"
        torch_dtype = torch.bfloat16

        self.processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForCausalLM.from_pretrained(
                model_id,
                torch_dtype=torch_dtype,
                low_cpu_mem_usage=True,
                trust_remote_code=True,
                device_map="auto"
            ).eval()
        else:
            self.model = AutoModelForCausalLM.from_pretrained(
                model_id,
                torch_dtype=torch_dtype,
                low_cpu_mem_usage=True,
                trust_remote_code=True
            ).to(device).eval()

        if self.processor.tokenizer.pad_token is None:
            self.processor.tokenizer.pad_token = self.processor.tokenizer.eos_token

        self.max_new_tokens = self.config.get('max_new_tokens', 100)

    def preprocess(self, input_image_and_questions):
        images = [Image.open(item[0]).convert('RGB') for item in input_image_and_questions]
        questions = [item[1] for item in input_image_and_questions]
        prompts = [f"[INST] <image>\n{q} [/INST]" for q in questions]
        
        return self.processor(text=prompts, images=images, return_tensors="pt", padding=True, truncation=True)

    def predict(self, model_input):
        return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens, pad_token_id=self.processor.tokenizer.eos_token_id)

    def postprocess(self, model_output):
        outputs = self.processor.batch_decode(model_output, skip_special_tokens=True)
        return [output.split('[/INST]')[1].strip() if '[/INST]' in output else output for output in outputs]
