# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoImageProcessor, AutoModelForUniversalSegmentation
from PIL import Image

class PyTorch_Transformers_OneFormer_ADE20K_Swin_Tiny(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "shi-labs/oneformer_ade20k_swin_tiny"

        # This model supports 'semantic', 'instance', and 'panoptic' tasks.
        # Defaulting to 'semantic' for this semantic segmentation context.
        self.task = self.config.get("task", "semantic")

        self.processor = AutoImageProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForUniversalSegmentation.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForUniversalSegmentation.from_pretrained(model_id)

    def preprocess(self, input_images):
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        # Store original sizes for postprocessing
        self.target_sizes = [img.size[::-1] for img in images] # (height, width)
        task_inputs = [self.task] * len(images)
        model_input = self.processor(images=images, task_inputs=task_inputs, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        predicted_semantic_maps = self.processor.post_process_semantic_segmentation(model_output, target_sizes=self.target_sizes)
        return [p.tolist() for p in predicted_semantic_maps]
