# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import QwenImageEditPipeline
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_QwenImageEdit(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Qwen/Qwen-Image-Edit"

        self.pipeline = QwenImageEditPipeline.from_pretrained(
            model_id,
            torch_dtype=torch.bfloat16
        )

        self.seed = self.config.get('seed', 0)
        self.num_inference_steps = self.config.get('num_inference_steps', 50)
        self.true_cfg_scale = self.config.get('true_cfg_scale', 4.0)
        self.negative_prompt = self.config.get('negative_prompt', " ")
        self.device = None
        self.generator = None

    def preprocess(self, input_images_and_prompts):
        images = []
        prompts = []
        for img_path, prompt in input_images_and_prompts:
            images.append(Image.open(img_path).convert('RGB'))
            prompts.append(prompt)
        
        # The pipeline expects a list of images and a list of prompts for batching
        return {"image": images, "prompt": prompts}

    def predict(self, model_input):
        model_input["generator"] = self.generator
        model_input["num_inference_steps"] = self.num_inference_steps
        model_input["true_cfg_scale"] = self.true_cfg_scale
        model_input["negative_prompt"] = self.negative_prompt

        with torch.inference_mode():
            output = self.pipeline(**model_input)
        
        return output.images

    def postprocess(self, model_output):
        # The pipeline returns a list of PIL Images
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)
        self.generator = torch.Generator(device=device).manual_seed(self.seed)

    def eval(self):
        # Pipelines are in eval mode by default. This is for API consistency.
        # The example shows disabling the progress bar, which is good for non-interactive use.
        self.pipeline.set_progress_bar_config(disable=True)

