# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import PaliGemmaProcessor, PaliGemmaForConditionalGeneration
from PIL import Image
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_Gemma_3n_E4B_it(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        # The requested model 'lmstudio-community/gemma-3n-E4B-it-MLX-bf16' is an MLX-quantized version.
        # We use the original PyTorch-compatible base model 'google/gemma-3n-E4B-it' instead.
        model_id = "google/gemma-3n-E4B-it"
        self.processor = PaliGemmaProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = PaliGemmaForConditionalGeneration.from_pretrained(model_id, device_map="auto", torch_dtype=torch.bfloat16)
        else:
            self.model = PaliGemmaForConditionalGeneration.from_pretrained(model_id, torch_dtype=torch.bfloat16)

        self.max_new_tokens = self.config.get('max_new_tokens', 100)

    def preprocess(self, input_image_and_questions):
        images = [Image.open(item[0]).convert('RGB') for item in input_image_and_questions]
        prompts = [item[1] for item in input_image_and_questions]
        return self.processor(text=prompts, images=images, return_tensors="pt", padding="longest")

    def predict(self, model_input):
        # Isolate the generated tokens from the input prompt
        input_len = model_input["input_ids"].shape[1]
        generation = self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)
        return generation[:, input_len:]

    def postprocess(self, model_output):
        # Decode only the newly generated tokens
        return self.processor.batch_decode(model_output, skip_special_tokens=True)
