# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
import librosa

class PyTorch_Transformers_Parakeet_TDT_CTC_110m(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        self.processor = Wav2Vec2Processor.from_pretrained("nvidia/parakeet-tdt_ctc-110m")
        
        if multi_gpu and device == "cuda":
            self.model = Wav2Vec2ForCTC.from_pretrained("nvidia/parakeet-tdt_ctc-110m", device_map="auto", torch_dtype="auto")
        else:
            self.model = Wav2Vec2ForCTC.from_pretrained("nvidia/parakeet-tdt_ctc-110m")

        self.sampling_rate = self.config.get('sampling_rate', 16_000)

    def preprocess(self, input_audios):
        for i in range(len(input_audios)):
            input_audios[i], _ = librosa.load(input_audios[i], sr=self.sampling_rate)
        model_input = self.processor(input_audios, sampling_rate=self.sampling_rate, return_tensors="pt", padding="longest")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input).logits

    def postprocess(self, model_output):
        predicted_ids = torch.argmax(model_output, dim=-1)
        return self.processor.batch_decode(predicted_ids)
