# Use TensorFlow GPU base image
FROM tensorflow/tensorflow:2.10.1-gpu

LABEL maintainer="Changjae Lee <changjae@buffalo.edu>" \
      build_date="${BUILD_DATE}" \
      vcs_ref="${VCS_REF}" \
      vcs_url="${VCS_URL}" \
      version="${VERSION}" \
      architecture="${ARCH}"

ARG TZ=America/New_York

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive \
    PYTHON_VERSION=3.7

# Install system dependencies and Python 3.7
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git build-essential wget curl libopenblas-dev software-properties-common && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get install -y python3.7 python3.7-distutils python3.7-dev && \
    apt-get install -y python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Update Python alternatives
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1 && \
    update-alternatives --config python <<< '1' && \
    python --version

# Upgrade pip and install Python packages
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir tensorflow-hub && \
    pip install --no-cache-dir transformers sentencepiece opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp-proto-grpc grpcio opentelemetry-exporter-otlp-proto-http httpio aenum requests tqdm scipy chardet psycopg "psycopg[binary]" Pika opencv-python-headless librosa && \
    pip install --no-cache-dir protobuf==3.20.* Pillow

# Clone py-mlmodelscope repository
RUN git clone https://github.com/xlab-ub/py-mlmodelscope.git /py-mlmodelscope

WORKDIR /py-mlmodelscope
ENTRYPOINT ["python", "run_mlmodelscope.py", "--standalone", "true", "--agent", "tensorflow"]

CMD ["--architecture", "gpu", "--model_name", "resnet50_keras"]