# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import AutoPipelineForInpainting
from PIL import Image
import io

class PyTorch_Diffusers_StableDiffusionXL_Inpainting_0_1(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "diffusers/stable-diffusion-xl-1.0-inpainting-0.1"
        if multi_gpu and device == "cuda":
            self.pipeline = AutoPipelineForInpainting.from_pretrained(model_id, torch_dtype=torch.float16, variant="fp16")
        else:
            self.pipeline = AutoPipelineForInpainting.from_pretrained(model_id)
        
        self.num_inference_steps = self.config.get('num_inference_steps', 20)
        self.guidance_scale = self.config.get('guidance_scale', 8.0)
        self.strength = self.config.get('strength', 0.99)

    def preprocess(self, input_prompts):
        prompts = [p['prompt'] for p in input_prompts]
        images = [Image.open(io.BytesIO(p['image'])).convert("RGB").resize((1024, 1024)) for p in input_prompts]
        mask_images = [Image.open(io.BytesIO(p['mask_image'])).convert("RGB").resize((1024, 1024)) for p in input_prompts]
        return {"prompt": prompts, "image": images, "mask_image": mask_images}

    def predict(self, model_input):
        generator = torch.Generator(device=self.device).manual_seed(0)
        return self.pipeline(
            **model_input,
            num_inference_steps=self.num_inference_steps,
            guidance_scale=self.guidance_scale,
            strength=self.strength,
            generator=generator
        ).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
