# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import LayoutLMv2Processor, LayoutLMv2ForQuestionAnswering
from PIL import Image
import torch

class PyTorch_Transformers_CIVQA_LayoutLMv2_EasyOCR(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Sharka/CIVQA_LayoutLMv2_EasyOCR"
        self.processor = LayoutLMv2Processor.from_pretrained(model_id)
        self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id)
        self.model.to(device)

    def preprocess(self, input_document_images_and_questions):
        images = [Image.open(p).convert("RGB") for p, q in input_document_images_and_questions]
        questions = [q for p, q in input_document_images_and_questions]
        return self.processor(images, questions, return_tensors="pt", padding=True, truncation=True)

    def predict(self, model_input):
        model_input = {k: v.to(self.model.device) for k, v in model_input.items()}
        outputs = self.model(**model_input)
        return outputs, model_input

    def postprocess(self, model_output):
        model_output, model_input = model_output_and_input
        start_logits = model_output.start_logits
        end_logits = model_output.end_logits

        start_indices = torch.argmax(start_logits, dim=1)
        end_indices = torch.argmax(end_logits, dim=1)

        answers = []
        for i in range(len(start_indices)):
            input_ids = model_input["input_ids"][i]
            start_index = start_indices[i]
            end_index = end_indices[i]
            
            if start_index <= end_index:
                answer_tokens = input_ids[start_index : end_index + 1]
                answer = self.processor.tokenizer.decode(answer_tokens, skip_special_tokens=True)
                answers.append(answer.strip())
            else:
                answers.append("")

        return answers
