# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_LaonA2_VL_3B(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "laonML/LaonA2_VL_3B"

        self.processor = AutoImageProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForObjectDetection.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForObjectDetection.from_pretrained(model_id)

    def preprocess(self, input_images):
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        self.target_sizes = torch.tensor([img.size[::-1] for img in images])
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        threshold = self.config.get("threshold", 0.5)
        # Assuming batch size is 1
        results = self.processor.post_process_object_detection(model_output, threshold=threshold, target_sizes=self.target_sizes)[0]
        scores = results['scores'].tolist()
        labels = results['labels'].tolist()
        boxes = results['boxes'].tolist()
        return [scores], [labels], [boxes]
