# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image

class PyTorch_Transformers_LaonA2_VL_3B(PyTorchAbstractClass):
    def __init__(selfconfig: dict):
        super().__init__(config)
        self.processor = AutoImageProcessor.from_pretrained('laonML/LaonA2_VL_3B')
        self.load_hf_model(AutoModelForObjectDetection, 'laonML/LaonA2_VL_3B')

    def preprocess(self, input_images):
        images = []
        for image_path in input_images:
            images.append(Image.open(image_path).convert("RGB"))
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        return [model_output[0]['scores'].tolist()], [model_output[0]['labels'].tolist()], [model_output[0]['boxes'].tolist()]
