# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch

class PyTorch_Transformers_CLIP_ViT_B_32_Laion2B(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "laion/CLIP-ViT-B-32-laion2B-s34B-b79K"
        self.processor = CLIPProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = CLIPModel.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = CLIPModel.from_pretrained(model_id)
            self.model.to(device)
        
        self.model.eval()

        # Download and prepare ImageNet labels for zero-shot classification
        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)

        # Pre-tokenize the text labels using a standard template for better performance.
        # They will be moved to the correct device in the predict step.
        imagenet_templates = [f"a photo of a {label}" for label in self.features]
        self.text_inputs = self.processor(text=imagenet_templates, return_tensors="pt", padding=True)

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        # The processor handles resizing, cropping, normalization, and conversion to tensor
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input.pixel_values

    def predict(self, model_input):
        # model_input is the pixel_values tensor from the preprocess step
        # Move text inputs to the same device as the model's image inputs
        # This is robust for both single-GPU and multi-GPU (device_map) setups
        device = model_input.device
        text_input_ids = self.text_inputs.input_ids.to(device)
        text_attention_mask = self.text_inputs.attention_mask.to(device)

        with torch.no_grad():
            outputs = self.model(pixel_values=model_input, input_ids=text_input_ids, attention_mask=text_attention_mask)
        
        return outputs

    def postprocess(self, model_output):
        # model_output is the full output object from the CLIPModel
        # We need the logits_per_image which represent the similarity scores between the image and each text label
        logits_per_image = model_output.logits_per_image
        
        # Apply softmax to convert scores to probabilities
        probabilities = torch.nn.functional.softmax(logits_per_image, dim=1)
        
        return probabilities.tolist()
