# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import LayoutLMv2Processor, LayoutLMv2ForQuestionAnswering
from PIL import Image
import torch

class PyTorch_Transformers_LayoutLMv2_Base_Uncased_Finetuned_InfoVQA(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        self.config.pop("_multi_gpu", False)

        model_id = "tiennvcs/layoutlmv2-base-uncased-finetuned-infovqa"
        self.processor = LayoutLMv2Processor.from_pretrained(model_id)
        self.model = LayoutLMv2ForQuestionAnswering.from_pretrained(model_id)
        self.model.to(device)
        self.device = device

    def preprocess(self, input_document_images_and_questions):
        images, questions = [], []
        for input_image, question in input_document_images_and_questions:
            images.append(Image.open(input_image).convert("RGB"))
            questions.append(question)

        encoding = self.processor(images, questions, return_tensors="pt", padding="max_length", truncation=True)
        self.last_encoding = encoding
        model_input = {k: v.to(self.device) for k, v in encoding.items()}
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        start_logits = model_output.start_logits.cpu()
        end_logits = model_output.end_logits.cpu()
        input_ids = self.last_encoding.input_ids

        start_indices = torch.argmax(start_logits, dim=1)
        end_indices = torch.argmax(end_logits, dim=1)

        answers = []
        for i in range(len(start_indices)):
            start_idx = start_indices[i]
            end_idx = end_indices[i]
            
            if start_idx > end_idx:
                answers.append("")
                continue
                
            answer_ids = input_ids[i][start_idx:end_idx+1]
            answer = self.processor.tokenizer.decode(answer_ids, skip_special_tokens=True)
            answers.append(answer.strip())

        return answers
