# Use a minimal Python base image
FROM python:3.8-slim

LABEL maintainer="Changjae Lee <changjae@buffalo.edu>" \
      build_date="${BUILD_DATE}" \
      vcs_ref="${VCS_REF}" \
      vcs_url="${VCS_URL}" \
      version="${VERSION}" \
      architecture="${ARCH}"

ARG TZ=America/New_York

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

# Install system dependencies and set timezone
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git build-essential ca-certificates wget curl libopenblas-dev && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir transformers diffusers sentencepiece opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp-proto-grpc grpcio opentelemetry-exporter-otlp-proto-http httpio aenum requests tqdm scipy chardet psycopg "psycopg[binary]" Pika opencv-python-headless 

# Clone py-mlmodelscope repository
RUN git clone https://github.com/xlab-ub/py-mlmodelscope.git /py-mlmodelscope

WORKDIR /py-mlmodelscope
ENTRYPOINT ["python", "run_mlmodelscope.py", "--standalone", "true", "--agent", "pytorch"]

CMD ["--architecture", "cpu"]