# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import Qwen2VLProcessor, Qwen2VLForConditionalGeneration
from PIL import Image
import torch

class PyTorch_Transformers_Qwen2VL_olmOCR(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "allenai/olmOCR-7B-0825"

        self.processor = Qwen2VLProcessor.from_pretrained(model_id, trust_remote_code=True)

        if multi_gpu and device == "cuda":
            self.model = Qwen2VLForConditionalGeneration.from_pretrained(
                model_id,
                device_map="auto",
                torch_dtype="auto",
                trust_remote_code=True
            )
        else:
            self.model = Qwen2VLForConditionalGeneration.from_pretrained(
                model_id,
                trust_remote_code=True
            )

        self.prompt = self.config.get('prompt', "Transcribe the document.")
        self.max_new_tokens = self.config.get('max_new_tokens', 1024)

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]

        # The Qwen-VL model expects a chat-like input. We construct it here.
        # We assume a single prompt for the entire batch of images.
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image"},
                    {"type": "text", "text": self.prompt}
                ]
            }
        ]
        text_prompt = self.processor.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        # The processor handles a batch of images with a corresponding list of texts.
        # We use the same text prompt for all images in the batch.
        model_input = self.processor(
            text=[text_prompt] * len(images),
            images=images,
            return_tensors="pt"
        )
        return model_input

    def predict(self, model_input):
        # The model input is a dictionary, so we unpack it with **
        return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        # The generated output includes the prompt. skip_special_tokens=True cleans up control tokens.
        preds = self.processor.batch_decode(model_output, skip_special_tokens=True)
        return [pred.strip() for pred in preds]
