# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForSemanticSegmentation
from PIL import Image

class PyTorch_Transformers_SegFormer_B0_Cityscapes(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "nvidia/segformer-b0-finetuned-cityscapes-1024-1024"

        self.processor = AutoImageProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForSemanticSegmentation.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForSemanticSegmentation.from_pretrained(model_id)

    def preprocess(self, input_images):
        images = [Image.open(path).convert("RGB") for path in input_images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        return model_output.logits.argmax(dim=1).tolist()
