# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from PIL import Image
import timm
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class Timm_ViT_Base_Patch32_384(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        model_id = "timm/vit_base_patch32_384.augreg_in21k_ft_in1k"

        self.model = timm.create_model(model_id, pretrained=True)
        self.model.eval()

        data_config = timm.data.resolve_model_data_config(self.model)
        self.transforms = timm.data.create_transform(**data_config, is_training=False)

        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)

    def preprocess(self, input_images):
        processed_images = []
        for image_path in input_images:
            image = Image.open(image_path).convert('RGB')
            processed_image = self.transforms(image)
            processed_images.append(processed_image)
        
        model_input = torch.stack(processed_images)
        return model_input

    def predict(self, model_input):
        return self.model(model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output, dim=1)
        return probabilities.tolist()
