# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import FluxPipeline

class PyTorch_Diffusers_FLUX_1_Dev(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        if multi_gpu and device == "cuda":
            self.pipeline = FluxPipeline.from_pretrained("lovis93/testllm", torch_dtype=torch.bfloat16)
        else:
            self.pipeline = FluxPipeline.from_pretrained("lovis93/testllm")

        self.height = self.config.get('height', 1024)
        self.width = self.config.get('width', 1024)
        self.guidance_scale = self.config.get('guidance_scale', 3.5)
        self.num_inference_steps = self.config.get('num_inference_steps', 50)
        self.max_sequence_length = self.config.get('max_sequence_length', 512)

    def preprocess(self, input_prompts):
        return input_prompts

    def predict(self, model_input):
        generator = torch.Generator(self.device).manual_seed(0)
        return self.pipeline(
            prompt=model_input,
            height=self.height,
            width=self.width,
            guidance_scale=self.guidance_scale,
            num_inference_steps=self.num_inference_steps,
            max_sequence_length=self.max_sequence_length,
            generator=generator
        ).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
