# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection
from PIL import Image

class PyTorch_Transformers_OwlvitBasePatch32Qint8(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "Gunulhona/owlvit-base-patch32-qint8"

        self.processor = AutoProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id)

    def preprocess(self, input_images):
        text_queries = kwargs.get("text_queries")
        if not text_queries:
            raise ValueError("text_queries must be provided for zero-shot object detection via kwargs")
        
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        self.target_sizes = torch.tensor([img.size[::-1] for img in images])
        
        model_input = self.processor(text=text_queries, images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        threshold = self.config.get("threshold", 0.1)
        results = self.processor.post_process_object_detection(outputs=model_output, target_sizes=self.target_sizes, threshold=threshold)
        
        # Assuming batch size is 1
        result = results[0]
        scores = result["scores"].tolist()
        labels = result["labels"].tolist()
        boxes = result["boxes"].tolist()
        
        return [scores], [labels], [boxes]
