# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import LayoutXLMProcessor, LayoutXLMForQuestionAnswering
from PIL import Image
import torch

class PyTorch_Transformers_CIVQA_layoutXLM_model(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "fimu-docproc-research/CIVQA_layoutXLM_model"
        self.processor = LayoutXLMProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = LayoutXLMForQuestionAnswering.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = LayoutXLMForQuestionAnswering.from_pretrained(model_id)
        
        self.last_encoding = None

    def preprocess(self, input_document_images_and_questions):
        images, questions = [], []
        for input_image, question in input_document_images_and_questions:
            images.append(Image.open(input_image).convert('RGB'))
            questions.append(question)
        encoding = self.processor(images, questions, return_tensors="pt", padding="max_length", truncation=True)
        return encoding

    def predict(self, model_input):
        self.last_encoding = model_input
        return self.model(**model_input)

    def postprocess(self, model_output):
        outputs = model_output
        encoding = self.last_encoding

        start_indices = torch.argmax(outputs.start_logits, dim=1)
        end_indices = torch.argmax(outputs.end_logits, dim=1)

        answers = []
        for i in range(len(start_indices)):
            start_idx = start_indices[i]
            end_idx = end_indices[i]

            if start_idx > end_idx:
                answers.append("")
                continue

            input_id_slice = encoding.input_ids[i][start_idx : end_idx + 1]
            answer = self.processor.tokenizer.decode(input_id_slice, skip_special_tokens=True)
            answers.append(answer.strip())

        return answers
