# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
import numpy as np
from PIL import Image
from transformers import AutoImageProcessor, Swin2srForImageSuperResolution
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Swin2SR_SuperResolution(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "caidas/swin2SR-realworld-sr-x4-64-bsrgan-psnr"
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = Swin2srForImageSuperResolution.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = Swin2srForImageSuperResolution.from_pretrained(model_id)

    def preprocess(self, input_images):
        images = [Image.open(img_path).convert('RGB') for img_path in input_images]
        return self.processor(images, return_tensors="pt")

    def predict(self, model_input):
        with torch.no_grad():
            return self.model(**model_input)

    def postprocess(self, model_output):
        reconstructions = model_output.reconstruction
        output_images = []
        for recon in reconstructions:
            output_image = recon.data.squeeze().float().cpu().clamp_(0, 1).permute(1, 2, 0)
            output_image = (output_image * 255.0).round().numpy().astype(np.uint8)
            output_images.append(output_image.tolist())
        return output_images

    def to(self, device):
        self.model.to(device)

    def eval(self):
        self.model.eval()
