# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoVideoProcessor, AutoModel
import av
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_Vjepa2_Vitl_Fpc64_256(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "facebook/vjepa2-vitl-fpc64-256"
        self.processor = AutoVideoProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModel.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModel.from_pretrained(model_id)

        # This model is a feature extractor and does not have classification labels.
        self.features = []

    def preprocess(self, input_videos):
        container = av.open(input_videos[0])
        # V-JEPA 2 models expect 64 frames as input
        indices = self.sample_frame_indices(clip_len=64, frame_sample_rate=1, seg_len=container.streams.video[0].frames)
        video = self.read_video_pyav(container, indices)
        # The processor expects a list of frames (e.g., from a video)
        model_input = self.processor(videos=list(video), return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        # This model is a feature extractor and returns embeddings, not classification logits.
        # We return the pooled output which represents the video embedding.
        return model_output.pooler_output.tolist()
