# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_OwlV2_Large_Patch14_Ensemble_ONNX(PyTorchAbstractClass):
    def __init__(selfconfig: dict):
        super().__init__(config)
        base_model_id = "google/owlv2-large-patch14-ensemble"
        model_id = "ioquioweknaskjdykasqwe12/owlv2-large-patch14-ensemble-ONNX"
        self.processor = AutoImageProcessor.from_pretrained(base_model_id)
        self.load_hf_model(AutoModelForObjectDetection, model_id)

    def preprocess(self, input_images):
        texts = kwargs.get("texts")
        if not texts:
            raise ValueError("This is a zero-shot model. Please provide text queries via the 'texts' keyword argument.")
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        self.target_sizes = [img.size[::-1] for img in images]
        model_input = self.processor(text=[texts for _ in images], images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor(self.target_sizes)
        results = self.processor.post_process_object_detection(outputs=model_output, target_sizes=target_sizes, threshold=0.1)
        scores = results[0]["scores"].tolist()
        labels = results[0]["labels"].tolist()
        boxes = results[0]["boxes"].tolist()
        return [scores], [labels], [boxes]
