# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch

class PyTorch_Transformers_CLIP_ViT_B_16_DataComp(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "laion/CLIP-ViT-B-16-DataComp.XL-s13B-b90K"
        self.processor = CLIPProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = CLIPModel.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = CLIPModel.from_pretrained(model_id)
            self.model.to(device)

        self.model.eval()

        # Use ImageNet classes as default for zero-shot classification
        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)
        # CLIP works best with descriptive text prompts
        self.candidate_labels = [f"a photo of a {label}" for label in self.features]

        # Pre-compute text features for the candidate labels
        text_inputs = self.processor(text=self.candidate_labels, return_tensors="pt", padding=True)
        # Move text inputs to the same device as the model
        text_inputs = {k: v.to(self.model.device) for k, v in text_inputs.items()}

        with torch.no_grad():
            self.text_features = self.model.get_text_features(**text_inputs)
            self.text_features /= self.text_features.norm(dim=-1, keepdim=True)

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(text=None, images=processed_images, return_tensors="pt")
        return model_input.pixel_values

    def predict(self, model_input):
        with torch.no_grad():
            image_features = self.model.get_image_features(pixel_values=model_input)
        return image_features

    def postprocess(self, model_output):
        # model_output contains the image features from the predict step
        image_features = model_output
        image_features /= image_features.norm(dim=-1, keepdim=True)

        # Compute cosine similarity between image and pre-computed text features
        logit_scale = self.model.logit_scale.exp()
        logits_per_image = logit_scale * image_features @ self.text_features.t()

        # Apply softmax to get probabilities
        probabilities = logits_per_image.softmax(dim=-1)
        return probabilities.tolist()
