# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from paddleocr import TextRecognition

class PyTorch_PaddleOCR_en_PP_OCRv5_mobile_rec(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        # device and multi_gpu are not directly used by paddleocr's TextRecognition class constructor,
        # but we extract them for consistency. paddleocr may use environment variables like CUDA_VISIBLE_DEVICES.
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        # The model_name is specific to the paddleocr library, not a Hugging Face path.
        self.model = TextRecognition(model_name="en_PP-OCRv5_mobile_rec")
        
        self.batch_size = self.config.get('batch_size', 1)

    def preprocess(self, input_images):
        # The paddleocr predict method directly accepts a list of image file paths.
        # No image loading or tensor conversion is needed here.
        return input_images

    def predict(self, model_input):
        # The model_input is a list of image paths from the preprocess step.
        return self.model.predict(input=model_input, batch_size=self.batch_size)

    def postprocess(self, model_output):
        # The model_output is a list of TextRecognitionResult objects.
        # We need to extract the recognized text from each result object.
        # Each result object has a 'res' attribute which is a dictionary containing 'rec_text'.
        preds = [result.res['rec_text'] for result in model_output]
        return [pred.strip() for pred in preds]
