# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import SpeechT5Processor, SpeechT5ForTextToSpeech, SpeechT5HifiGan
import torch
from datasets import load_dataset

class PyTorch_Transformers_SpeechT5_TTS_Vietnamese(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "GinNoV111/speecht5_finetuned_tts_vietnamese"

        self.processor = SpeechT5Processor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = SpeechT5ForTextToSpeech.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = SpeechT5ForTextToSpeech.from_pretrained(model_id)
            self.model.to(device)

        self.vocoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan")
        self.vocoder.to(device)

        embeddings_dataset = load_dataset("Matthijs/cmu-arctic-xvectors", split="validation")
        self.speaker_embeddings = torch.tensor(embeddings_dataset[7306]["xvector"]).unsqueeze(0)
        self.speaker_embeddings.to(device)

        self.features = {"sampling_rate": self.vocoder.config.sampling_rate}

    def preprocess(self, input_texts):
        inputs = self.processor(text=input_texts, return_tensors="pt", padding=True)
        inputs["speaker_embeddings"] = self.speaker_embeddings
        return inputs

    def predict(self, model_input):
        spectrogram = self.model.generate_speech(model_input["input_ids"], speaker_embeddings=model_input["speaker_embeddings"])
        with torch.no_grad():
            audio = self.vocoder(spectrogram)
        return audio

    def postprocess(self, model_output):
        return model_output.cpu().numpy().tolist()
