# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusionImg2ImgPipeline, UNet2DConditionModel
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_RealisticVision_Img2Img(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        base_model_id = "runwayml/stable-diffusion-v1-5"
        unet_model_id = "refiners/sd15.realistic_vision.v5_1.unet"

        torch_dtype = torch.float16 if "cuda" in device else torch.float32

        # Load the custom UNet component
        unet = UNet2DConditionModel.from_pretrained(unet_model_id, torch_dtype=torch_dtype)

        # Load the base pipeline and inject the custom UNet
        self.pipeline = StableDiffusionImg2ImgPipeline.from_pretrained(
            base_model_id,
            unet=unet,
            torch_dtype=torch_dtype
        )

    def preprocess(self, input_images_and_prompts):
        images = []
        prompts = []
        for img_path, prompt in input_images_and_prompts:
            images.append(Image.open(img_path).convert('RGB'))
            prompts.append(prompt)
        return {"image": images, "prompt": prompts}

    def predict(self, model_input):
        return self.pipeline(**model_input).images

    def postprocess(self, model_output):
        # The pipeline output is a list of PIL images
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        # The pipeline handles setting the model to eval mode internally
        pass
