# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForSemanticSegmentation
from PIL import Image
import torch

class PyTorch_Transformers_CIDAS_clipseg_rd64_refined(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "CIDAS/clipseg-rd64-refined"
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForSemanticSegmentation.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForSemanticSegmentation.from_pretrained(model_id)

    def preprocess(self, input_images):
        images = [Image.open(path).convert("RGB") for path in input_images]
        # CLIPSeg requires text prompts. These can be provided in the config.
        # Example: config={"texts": ["a cat", "a dog"]}
        texts = self.config.get("texts", ["a photo of a cat"]) # Default prompt
        model_input = self.processor(text=texts, images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        # For CLIPSeg, the output is typically a single logit map per prompt.
        # We apply a sigmoid and threshold to get a binary mask.
        # If multiple prompts are used, you might need to handle multiple output masks.
        masks = torch.sigmoid(model_output.logits).squeeze(1)
        binary_masks = (masks > 0.5).int()
        return binary_masks.tolist()
