# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_OwlvitBasePatch32(PyTorchAbstractClass):
    def __init__(self):
        super().__init__(config)
        self.processor = AutoImageProcessor.from_pretrained("rathi2023/owlvit-base-patch32")
        self.model = self.load_hf_model(AutoModelForObjectDetection, "rathi2023/owlvit-base-patch32")

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]
        self.target_sizes = torch.tensor([img.size[::-1] for img in images])
        # This model requires text prompts for zero-shot detection.
        # Using placeholder prompts. Modify as needed for your use case.
        texts = [["a photo of a cat", "a photo of a dog"]] * len(images)
        model_input = self.processor(text=texts, images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        results = self.processor.post_process_object_detection(outputs=model_output, threshold=0.1, target_sizes=self.target_sizes)
        # Postprocessing assumes a batch size of 1
        i = 0
        scores = results[i]["scores"].tolist()
        labels = results[i]["labels"].tolist()
        boxes = results[i]["boxes"].tolist()
        return [scores], [labels], [boxes]
