# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForImageClassification
from PIL import Image
import torch

class PyTorch_Transformers_Eva02_Enormous_Patch14_Plus_Clip_224(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        
        model_id = "timm/eva02_enormous_patch14_plus_clip_224.laion2b_s9b_b144k"
        self.processor = AutoImageProcessor.from_pretrained(model_id, trust_remote_code=True)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForImageClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto", trust_remote_code=True)
        else:
            self.model = AutoModelForImageClassification.from_pretrained(model_id, trust_remote_code=True)
        
        self.model.eval()

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
