# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import ParakeetForCTC, AutoProcessor
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
import librosa

class PyTorch_Transformers_Parakeet_TDT_0_6B_V2(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "nvidia/parakeet-tdt-0.6b-v2"

        self.processor = AutoProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = ParakeetForCTC.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = ParakeetForCTC.from_pretrained(model_id)

        self.sampling_rate = self.config.get('sampling_rate', 16_000)

    def preprocess(self, input_audios):
        for i in range(len(input_audios)):
            input_audios[i], _ = librosa.load(input_audios[i], sr=self.sampling_rate)
        model_input = self.processor(audios=input_audios, sampling_rate=self.sampling_rate, return_tensors="pt", padding="longest")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input).logits

    def postprocess(self, model_output):
        predicted_ids = torch.argmax(model_output, dim=-1)
        return self.processor.batch_decode(predicted_ids)
