# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForImageClassification
from PIL import Image
import torch
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_SwinV2_Tiny_Patch4_Window16_256(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        model_id = "microsoft/swinv2-tiny-patch4-window16-256"
        
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        self.model = AutoModelForImageClassification.from_pretrained(model_id)
        self.model.eval()

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        with torch.no_grad():
            outputs = self.model(**model_input)
        return outputs

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
