# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoImageProcessor, AutoModelForDepthEstimation
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_Sam2_1_Hiera_Large(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "tictag-io-demo/sam2.1-hiera-large"

        self.image_processor = AutoImageProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForDepthEstimation.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForDepthEstimation.from_pretrained(model_id)

        self.original_sizes = None

    def preprocess(self, input_images):
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        self.original_sizes = [image.size for image in images]
        return self.image_processor(images, return_tensors="pt")

    def predict(self, model_input):
        return self.model(**model_input).predicted_depth

    def postprocess(self, model_output):
        predictions_resized = []
        for output, original_size in zip(model_output, self.original_sizes):
            # Interpolate to original size
            prediction = torch.nn.functional.interpolate(
                output.unsqueeze(0).unsqueeze(0),
                size=original_size[::-1],  # PIL size is (width, height), torch size is (height, width)
                mode="bicubic",
                align_corners=False,
            )
            # Normalize and convert to uint8
            output_np = prediction.squeeze().cpu().numpy()
            formatted = (output_np * 255 / np.max(output_np)).astype("uint8")
            predictions_resized.append(formatted.tolist())
        
        self.original_sizes = None
        return predictions_resized
