# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import warnings
import torch
from transformers import LlavaNextProcessor, LlavaNextForConditionalGeneration
from PIL import Image

class PyTorch_Transformers_Lin_Chen_sharegpt4video_8b(PyTorchAbstractClass):
    def __init__(self, config=None):
        warnings.warn("Currently, this model does not support batched forward with multiple images of different sizes.")
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Lin-Chen/sharegpt4video-8b"
        self.processor = LlavaNextProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = LlavaNextForConditionalGeneration.from_pretrained(model_id, device_map="auto", torch_dtype=torch.float16)
        else:
            self.model = LlavaNextForConditionalGeneration.from_pretrained(model_id, torch_dtype=torch.float16)

        self.processor.tokenizer.pad_token = self.processor.tokenizer.eos_token

        self.max_new_tokens = self.config.get('max_new_tokens', 100)

    def preprocess(self, input_image_and_questions):
        images = [Image.open(input_image_and_question[0]) for input_image_and_question in input_image_and_questions]
        prompts = [f"[INST] <image>\n{input_image_and_question[1]} [/INST]" for input_image_and_question in input_image_and_questions]
        return self.processor(text=prompts, images=images, return_tensors="pt", padding=True, truncation=True)

    def predict(self, model_input):
        return self.model.generate(**model_input, pad_token_id=self.processor.tokenizer.eos_token_id, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        return [output.split('[/INST]')[1].strip() for output in self.processor.batch_decode(model_output, skip_special_tokens=True)]
