# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch
import warnings

class PyTorch_Transformers_Xenova_owlv2_base_patch16_finetuned(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = 'Xenova/owlv2-base-patch16-finetuned'

        self.processor = AutoImageProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForObjectDetection.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForObjectDetection.from_pretrained(model_id)
        
        # This is a zero-shot model and requires candidate labels.
        # Provide them in the config, e.g., {"candidate_labels": ["cat", "dog"]}
        self.candidate_labels = self.config.get("candidate_labels", ["person", "car", "cat", "dog"])
        
        warnings.warn("The current implementation assumes a batch size of 1 for postprocessing.")

    def preprocess(self, input_images):
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        self.original_sizes = [img.size[::-1] for img in images] # (height, width)
        texts = [self.candidate_labels] * len(images)
        model_input = self.processor(text=texts, images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor(self.original_sizes)
        results = self.processor.post_process_object_detection(outputs=model_output, target_sizes=target_sizes)
        
        # Process results for the first image in the batch
        result = results[0]
        scores = result["scores"].tolist()
        labels = result["labels"].tolist()
        boxes = result["boxes"].tolist()
        
        return [scores], [labels], [boxes]
