# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, AutoModel
from PIL import Image
import torch

class PyTorch_Transformers_SigLIP2_Base_Patch16_224(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        
        model_id = "google/siglip2-base-patch16-224"
        self.processor = AutoProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModel.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModel.from_pretrained(model_id)
        
        self.model.eval()

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        with torch.no_grad():
            # This model is a vision encoder and outputs image embeddings (features),
            # not classification logits.
            model_output = self.model.get_image_features(**model_input)
        return model_output

    def postprocess(self, model_output):
        # The model outputs image embeddings, not classification logits.
        # Applying softmax is not applicable. Returning the raw embeddings as a list.
        return model_output.tolist()
