# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import Pix2StructProcessor, Pix2StructForConditionalGeneration
from PIL import Image

class PyTorch_Transformers_Pix2Struct_StructTable_Base(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        self.processor = Pix2StructProcessor.from_pretrained("U4R/StructTable-base")
        
        if multi_gpu and device == "cuda":
            self.model = Pix2StructForConditionalGeneration.from_pretrained("U4R/StructTable-base", device_map="auto", torch_dtype="auto")
        else:
            self.model = Pix2StructForConditionalGeneration.from_pretrained("U4R/StructTable-base")
        
        self.max_new_tokens = self.config.get('max_new_tokens', 512)

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input.pixel_values

    def predict(self, model_input):
        return self.model.generate(pixel_values=model_input, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        preds = self.processor.batch_decode(model_output, skip_special_tokens=True)
        return [pred.strip() for pred in preds]
