# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import DiffusionPipeline

class PyTorch_Diffusers_StableMaterials(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        self.pipeline = DiffusionPipeline.from_pretrained("gvecchio/StableMaterials", trust_remote_code=True, torch_dtype=torch.float16)
        self.num_inference_steps = self.config.get('num_inference_steps', 50)

    def preprocess(self, input_prompts):
        return input_prompts

    def predict(self, model_input):
        return self.pipeline(prompt=model_input, num_inference_steps=self.num_inference_steps, tileable=True).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
