# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import LayoutLMv3Processor, LayoutLMv3ForQuestionAnswering
from PIL import Image
import torch

class PyTorch_Transformers_Sharka_CIVQA_LayoutLMv3_EasyOCR(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        self.device = device
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Sharka/CIVQA_LayoutLMv3_EasyOCR"
        self.processor = LayoutLMv3Processor.from_pretrained(model_id)
        self.model = LayoutLMv3ForQuestionAnswering.from_pretrained(model_id)
        self.model.to(self.device)

    def preprocess(self, input_document_images_and_questions):
        images, questions = [], []
        for image_path, question in input_document_images_and_questions:
            images.append(Image.open(image_path).convert("RGB"))
            questions.append(question)
        return self.processor(images, questions, return_tensors="pt", padding="max_length", truncation=True)

    def predict(self, model_input):
        for k, v in model_input.items():
            model_input[k] = v.to(self.device)
        
        with torch.no_grad():
            outputs = self.model(**model_input)
        
        return {"start_logits": outputs.start_logits, "end_logits": outputs.end_logits, "input_ids": model_input["input_ids"]}

    def postprocess(self, model_output):
        start_logits = model_output["start_logits"]
        end_logits = model_output["end_logits"]
        input_ids = model_output["input_ids"]
        
        answers = []
        for i in range(len(start_logits)):
            start_index = torch.argmax(start_logits[i])
            end_index = torch.argmax(end_logits[i])
            
            answer_ids = input_ids[i][start_index:end_index+1]
            answer = self.processor.tokenizer.decode(answer_ids).strip()
            answers.append(answer)
            
        return answers
