# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_Xenova_OwlViT_Base_Patch16(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "Xenova/owlvit-base-patch16"

        self.processor = AutoProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id)

    def preprocess(self, input_images):
        self.image_paths = input_images
        images = [Image.open(img_path).convert("RGB") for img_path in self.image_paths]
        if "candidate_labels" not in self.config:
            raise ValueError("candidate_labels must be provided in the config for zero-shot object detection.")
        candidate_labels = self.config["candidate_labels"]
        texts = [candidate_labels for _ in images]
        model_input = self.processor(text=texts, images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor([Image.open(img_path).size[::-1] for img_path in self.image_paths])
        threshold = self.config.get("threshold", 0.1)
        results = self.processor.post_process_object_detection(outputs=model_output, threshold=threshold, target_sizes=target_sizes)
        result = results[0]
        scores = result["scores"].tolist()
        labels = result["labels"].tolist()
        boxes = result["boxes"].tolist()
        return [scores], [labels], [boxes]
