# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch

class PyTorch_Transformers_CLIP_ViT_Large_Patch14(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "openai/clip-vit-large-patch14"
        self.processor = CLIPProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = CLIPModel.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = CLIPModel.from_pretrained(model_id)
        
        self.model.eval()

        self.candidate_labels = self.config.get("candidate_labels")
        if not self.candidate_labels or not isinstance(self.candidate_labels, list):
            raise ValueError("CLIP model requires a list of 'candidate_labels' to be provided in the config dictionary for zero-shot classification.")

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]

        model_input = self.processor(
            text=self.candidate_labels,
            images=processed_images,
            return_tensors="pt",
            padding=True
        )
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits_per_image, dim=1)
        return probabilities.tolist()
