# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from dia.model import Dia
import torch

class PyTorch_Dia_1_6B(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "nari-labs/Dia-1.6B"

        dtype = torch.float16 if "cuda" in device else torch.float32

        if multi_gpu and "cuda" in device:
            self.model = Dia.from_pretrained(model_id, device_map="auto", torch_dtype=dtype)
        else:
            self.model = Dia.from_pretrained(model_id, torch_dtype=dtype).to(device)

        self.features = {"sampling_rate": 44100}

    def preprocess(self, input_texts):
        return {"text": input_texts}

    def predict(self, model_input):
        return self.model.generate(**model_input)

    def postprocess(self, model_output):
        return model_output.cpu().numpy().tolist()
