# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoProcessor, VideoMAEForVideoClassification
import av
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_MCG_NJU_VideoMAE_Base_Short_SSV2(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "MCG-NJU/videomae-base-short-ssv2"
        self.processor = AutoProcessor.from_pretrained(model_id)
        
        # ignore_mismatched_sizes is required to load a pre-trained backbone into a classification model
        if multi_gpu and device == "cuda":
            self.model = VideoMAEForVideoClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto", ignore_mismatched_sizes=True)
        else:
            self.model = VideoMAEForVideoClassification.from_pretrained(model_id, ignore_mismatched_sizes=True)

        # This is a base model without a pre-defined classification head.
        # We generate placeholder labels based on the default number of labels in the randomly initialized head.
        self.features = [f"label_{i}" for i in range(self.model.config.num_labels)]

    def preprocess(self, input_videos):
        container = av.open(input_videos[0])
        # Sample a clip of 16 frames
        indices = self.sample_frame_indices(clip_len=self.model.config.num_frames, frame_sample_rate=1, seg_len=container.streams.video[0].frames)
        video = self.read_video_pyav(container, indices)
        pixel_values = self.processor(videos=list(video), return_tensors="pt").pixel_values
        return pixel_values

    def predict(self, model_input):
        return self.model(model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
