"""
Generalized automation script for text-to-audio PyTorch models.

Supports: music generation, TTS/speech synthesis, sound effects generation,
audio manipulation, and more.

Usage:
    from automation import text_to_audio_model_automation

    text_to_audio_model_automation(
        models_to_add=["facebook/musicgen-small"],
        task_type="music_generation"
    )
"""

import os
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field
from langchain_core.output_parsers import JsonOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI


def text_to_audio_model_automation(models_to_add=None, task_type="music_generation"):
    """Generalized automation for text-to-audio tasks."""
    if models_to_add is None:
        return "No models specified for addition."

    MODEL_TEMPLATE = """# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

{imports}

class {class_name}(PyTorchAbstractClass):
    def __init__(self{init_config}):
        {init_body}

    def preprocess(self, input_texts):
        {preprocess_body}

    def predict(self, model_input):
        {predict_body}

    def postprocess(self, model_output):
        {postprocess_body}
"""

    class ModelConfig(BaseModel):
        """Configuration details for a PyTorch audio generation model."""

        imports: str = Field(
            description="The complete imports section. Typically: 'from transformers import AutoProcessor, MusicgenForConditionalGeneration' (or other audio gen models). Use proper formatting with newlines.",
            default="from transformers import AutoProcessor, MusicgenForConditionalGeneration",
        )

        class_name: str = Field(
            description="The class name for the model. Should be descriptive and follow PascalCase convention, e.g., 'PyTorch_Transformers_MusicGen_Small'.",
        )

        init_config: str = Field(
            description="The __init__ method signature parameters. Typically ', config=None' for audio generation models.",
            default=", config=None",
        )

        init_body: str = Field(
            description="The complete body of the __init__ method. Should include: 1) config initialization with super().__init__(config), 2) loading processor from_pretrained, 3) loading model using self.load_hf_model(ModelClass, model_id) for multi-GPU support, 4) setting generation parameters (max_new_tokens), 5) storing sampling_rate from model config in self.features dict. Include proper indentation (8 spaces).",
        )

        preprocess_body: str = Field(
            description="The complete body of the preprocess method. Should use processor with text=input_texts, return_tensors='pt', padding=True. The method receives input_texts (list of text prompts). Include proper indentation (8 spaces).",
        )

        predict_body: str = Field(
            description="The complete body of the predict method. Should call model.generate(**model_input, max_new_tokens=self.max_new_tokens). Include proper indentation (8 spaces).",
        )

        postprocess_body: str = Field(
            description="The complete body of the postprocess method. Should convert output to numpy array: model_output.cpu().numpy().squeeze(axis=1).tolist(). Include proper indentation (8 spaces).",
        )

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                f"""
You are an expert in PyTorch audio generation models. Your task is to generate a complete, working model.py file for a PyTorch audio generation wrapper class.

**IMPORTANT GUIDELINES:**

1. **Model Type Detection:**
   - MusicGen models: Use MusicgenForConditionalGeneration + AutoProcessor
   - AudioLDM models: Use AudioLDMPipeline or similar
   - Bark models: Use BarkModel + processor

2. **Imports:**
   - Always include: `from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass`
   - For MusicGen: `from transformers import AutoProcessor, MusicgenForConditionalGeneration`
   - Add other imports as needed

3. **Init Method:**
   - Initialize config: `super().__init__(config)` (required for load_hf_model to work)
   - Load processor: `AutoProcessor.from_pretrained(model_id)`
   - Load model: `self.model = self.load_hf_model(MusicgenForConditionalGeneration, model_id)` (use load_hf_model for multi-GPU support)
   - Set max_new_tokens from config (default 256 for MusicGen)
   - Store sampling_rate: `self.features = {{{{"sampling_rate": self.model.config.audio_encoder.sampling_rate}}}}`

4. **Preprocess Method:**
   - Input is text prompts: `return self.processor(text=input_texts, return_tensors="pt", padding=True)`

5. **Predict Method:**
   - Call generate: `return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)`

6. **Postprocess Method:**
   - Convert to list: `return model_output.cpu().numpy().squeeze(axis=1).tolist()`

**Reference Example:**

Example 1: MusicGen Model
{{{{
    "imports": "from transformers import AutoProcessor, MusicgenForConditionalGeneration",
    "class_name": "PyTorch_Transformers_MusicGen_Small",
    "init_config": ", config=None",
    "init_body": "super().__init__(config)\\n        model_id = \\"facebook/musicgen-small\\"\\n        self.processor = AutoProcessor.from_pretrained(model_id)\\n        self.model = self.load_hf_model(MusicgenForConditionalGeneration, model_id)\\n\\n        self.max_new_tokens = self.config.get('max_new_tokens', 256)\\n\\n        self.features = {{{{\\"sampling_rate\\": self.model.config.audio_encoder.sampling_rate}}}}",
    "preprocess_body": "return self.processor(text=input_texts, return_tensors=\\"pt\\", padding=True)",
    "predict_body": "return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)",
    "postprocess_body": "return model_output.cpu().numpy().squeeze(axis=1).tolist()"
}}}}

Respond ONLY with the JSON structure matching the ModelConfig schema.
""",
            ),
            (
                "human",
                """
Context from Hugging Face page:
---
{model_page_context}
---
Generate config for model: '{model_identifier}'

Use the exact model identifier '{model_identifier}' in the init_body.
""",
            ),
        ]
    )

    modelCounter = 0
    load_dotenv()
    if not os.getenv("GOOGLE_API_KEY"):
        raise EnvironmentError("GOOGLE_API_KEY not found.")

    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-pro",
        model_kwargs={"thinkingBudget": -1},
        temperature=0,
        convert_system_message_to_human=True,
    )
    parser = JsonOutputParser(pydantic_object=ModelConfig)
    chain = prompt | llm | parser

    BASE_DIR = f"mlmodelscope/pytorch_agent/models/default/{task_type}"
    ERROR_DIR = f"{BASE_DIR}/errors"
    os.makedirs(ERROR_DIR, exist_ok=True)
    failed_models = []
    login_req_models = []

    for model_name in models_to_add:
        if modelCounter == 50:
            break
        print(f"\n--- Processing model: {model_name} ---")

        model_folder_name = (
            model_name.split("/")[-1].replace("-", "_").replace(".", "_").lower()
        )
        model_py_path = os.path.join(BASE_DIR, model_folder_name, "model.py")

        if os.path.exists(model_py_path):
            print(f"Model '{model_folder_name}' already exists. Skipping.")
            continue

        error_log = ""
        try:
            check_syntax = lambda fn: os.system(f"python -m py_compile {fn}")
            error = False
            while not os.path.exists(model_py_path) or (
                error := check_syntax(model_py_path)
            ):
                if error:
                    error_log += f"Syntax error, regenerating...\n"

                url = f"https://huggingface.co/{model_name}"
                response = requests.get(url)
                response.raise_for_status()

                soup = BeautifulSoup(response.text, "html.parser")
                main_content = (
                    soup.find("model-card-content")
                    or soup.find("main")
                    or soup.find("body")
                )

                if not main_content:
                    break

                login_link = main_content.find(
                    "a", href=lambda h: h and h.startswith("/login?next=")
                )
                if login_link:
                    login_req_models.append(model_name)
                    break

                context_text = main_content.get_text(separator=" ", strip=True)
                if len(context_text) > 20000:
                    context_text = context_text[:20000] + "\n... (truncated)"

                model_config_dict = chain.invoke(
                    {
                        "model_identifier": model_name,
                        "model_page_context": context_text,
                    }
                )

                init_body = model_config_dict.get("init_body", "").replace(
                    "{hugging_face_model_id}", model_name
                )

                filled_template = MODEL_TEMPLATE.format(
                    imports=model_config_dict.get(
                        "imports",
                        "from transformers import AutoProcessor, MusicgenForConditionalGeneration",
                    ),
                    class_name=model_config_dict.get(
                        "class_name",
                        f"PyTorch_{task_type.replace('_', ' ').title().replace(' ', '_')}_Model",
                    ),
                    init_config=model_config_dict.get("init_config", ", config=None"),
                    init_body=init_body.lstrip(" "),
                    preprocess_body=model_config_dict.get(
                        "preprocess_body", "pass"
                    ).lstrip(" "),
                    predict_body=model_config_dict.get(
                        "predict_body", "return self.model.generate(**model_input)"
                    ).lstrip(" "),
                    postprocess_body=model_config_dict.get(
                        "postprocess_body", "return model_output.cpu().numpy().tolist()"
                    ).lstrip(" "),
                )

                model_dir = os.path.join(BASE_DIR, model_folder_name)
                os.makedirs(model_dir, exist_ok=True)

                with open(model_py_path, "w") as f:
                    f.write(filled_template)

            else:
                print(f"Successfully generated {model_py_path}")
                modelCounter += 1

        except Exception as e:
            print(f"Failed: {e}")
            import traceback

            traceback.print_exc()
            failed_models.append(model_name)

    print(f"\n--- Automation complete ---")
    with open(os.path.join(ERROR_DIR, "failed_models.log"), "w") as f:
        for fm in failed_models:
            f.write(f"{fm}\n")
    with open(os.path.join(ERROR_DIR, "login_req_models.log"), "w") as f:
        for lm in login_req_models:
            f.write(f"{lm}\n")


# Backward compatibility wrapper
def audio_generation_model_automation(models_to_add=None):
    """Legacy function name. Use text_to_audio_model_automation instead."""
    return text_to_audio_model_automation(models_to_add, "music_generation")


if __name__ == "__main__":
    # Music generation
    # text_to_audio_model_automation(
    #     models_to_add=["facebook/musicgen-small"],
    #     task_type="music_generation"
    # )

    # Speech synthesis / TTS
    text_to_audio_model_automation(
        models_to_add=["microsoft/speecht5_tts"], task_type="speech_synthesis"
    )
