# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch
from torchvision.ops import box_convert
import warnings

class PyTorch_Transformers_DETR_ResNet50_SKU110k(PyTorchAbstractClass):
    def __init__(self):
        super().__init__(config)
        warnings.warn("The batch size should be 1.")
        self.processor = AutoImageProcessor.from_pretrained("isalia99/detr-resnet-50-sku110k")
        self.load_hf_model(AutoModelForObjectDetection, "isalia99/detr-resnet-50-sku110k")

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        # Assuming batch size is 1
        probas = model_output.logits.softmax(-1)[0, :, :-1]
        scores = probas.max(-1).values
        labels = probas.argmax(-1)

        # Convert bounding boxes from (center_x, center_y, width, height) to (x1, y1, x2, y2)
        # The boxes are normalized and remain normalized after conversion.
        boxes = box_convert(model_output.pred_boxes[0], in_fmt="cxcywh", out_fmt="xyxy")

        return [scores.tolist()], [labels.tolist()], [boxes.tolist()]
