# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from audiocraft.models import MAGNeT
import torch

class PyTorch_Audiocraft_MAGNeT_Medium_30secs(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)  # Note: multi_gpu not directly supported by audiocraft loader

        self.model = MAGNeT.get_pretrained("facebook/magnet-medium-30secs")
        self.model.to(device)

        # Any remaining keys in self.config are treated as generation parameters
        self.generation_params = self.config

        self.features = {"sampling_rate": self.model.sample_rate}

    def preprocess(self, input_texts):
        # The model's generate method directly accepts a list of text prompts
        return input_texts

    def predict(self, model_input):
        # The model_input is the list of text prompts from preprocess
        return self.model.generate(model_input, **self.generation_params)

    def postprocess(self, model_output):
        # The output is a tensor of shape (batch_size, num_channels, sequence_length)
        # Convert to a list of numpy arrays for standard output
        return model_output.cpu().numpy().tolist()
