# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_GroundingDinoTiny(PyTorchAbstractClass):
    def __init__(selfconfig: dict):
        super().__init__(config)
        self.model_id = 'tonyshark/grounding-dino-tiny'
        self.processor = AutoImageProcessor.from_pretrained(self.model_id)
        self.model = self.load_hf_model(AutoModelForObjectDetection, self.model_id)
        self.original_sizes = None

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]
        self.original_sizes = [img.size[::-1] for img in images] # (height, width)
        # Grounding DINO requires a text prompt. Using a generic one as it's not provided by the framework.
        texts = ["an object ." for _ in images]
        model_input = self.processor(images=images, text=texts, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor(self.original_sizes)
        results = self.processor.post_process_object_detection(model_output, threshold=0.5, target_sizes=target_sizes)
        # Assuming batch size is 1
        result = results[0]
        scores = result['scores'].tolist()
        labels = result['labels'] # These are string labels from the prompt
        boxes = result['boxes'].tolist()
        return [scores], [labels], [boxes]
