# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoProcessor, Qwen2VLForConditionalGeneration
from PIL import Image

class PyTorch_Transformers_MinerU2_5_2509_1_2B(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "opendatalab/MinerU2.5-2509-1.2B"
        self.processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
        
        if multi_gpu and device == "cuda":
            self.model = Qwen2VLForConditionalGeneration.from_pretrained(model_id, device_map="auto", torch_dtype="auto", trust_remote_code=True)
        else:
            self.model = Qwen2VLForConditionalGeneration.from_pretrained(model_id, torch_dtype="auto", trust_remote_code=True)

        self.max_new_tokens = self.config.get('max_new_tokens', 100)

    def preprocess(self, input_image_and_questions):
        images = [Image.open(item[0]).convert('RGB') for item in input_image_and_questions]
        
        prompts = []
        for _, question in input_image_and_questions:
            messages = [
                {"role": "user", "content": f"<image>\n{question}"}
            ]
            prompt = self.processor.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            prompts.append(prompt)
            
        return self.processor(text=prompts, images=images, return_tensors="pt", padding=True)

    def predict(self, model_input):
        return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens, pad_token_id=self.processor.tokenizer.eos_token_id)

    def postprocess(self, model_output):
        decoded_outputs = self.processor.batch_decode(model_output, skip_special_tokens=True)
        return [output.split('assistant\n')[-1].strip() for output in decoded_outputs]
