# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor
import librosa
import torch

class PyTorch_Transformers_Granite_Speech_3_3_2b(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "ibm-granite/granite-speech-3.3-2b"
        self.processor = AutoProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForSpeechSeq2Seq.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForSpeechSeq2Seq.from_pretrained(model_id)

        self.sampling_rate = self.config.get('sampling_rate', 16_000)

    def preprocess(self, input_audios):
        audios = []
        for audio_path in input_audios:
            audio, _ = librosa.load(audio_path, sr=self.sampling_rate)
            audios.append(audio)

        prompts = ["<|audio|>can you transcribe the speech into a written format?"] * len(audios)

        model_input = self.processor(
            text=prompts, 
            audios=audios, 
            return_tensors="pt", 
            padding=True, 
            sampling_rate=self.sampling_rate
        )
        return model_input

    def predict(self, model_input):
        return self.model.generate(**model_input, max_new_tokens=256)

    def postprocess(self, model_output):
        return self.processor.batch_decode(model_output, skip_special_tokens=True)
