# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from PIL import Image
import open_clip

class PyTorch_Transformers_MobileCLIP_S2(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        self.device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = 'hf-hub:apple/MobileCLIP-S2-OpenCLIP'
        
        try:
             self.model, _, self.preprocess_fn = open_clip.create_model_and_transforms(model_id)
             self.tokenizer = open_clip.get_tokenizer(model_id)
        except Exception as e:
             raise ImportError(f"Failed to load OpenCLIP model: {e}")

        self.model.to(self.device)
        self.model.eval()

        self.labels = self.config.get("labels", [])
        if not self.labels or not isinstance(self.labels, list):
            features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
            self.labels = self.features_download(features_file_url)

        # Pre-tokenize labels
        text_tokens = self.tokenizer(self.labels).to(self.device)
        with torch.no_grad():
             self.text_features = self.model.encode_text(text_tokens)
             self.text_features /= self.text_features.norm(dim=-1, keepdim=True)

    def to(self, device, multi_gpu=False):
        self.model.to(device)
        self.device = device

    def preprocess(self, input_images):
        images = [
            self.preprocess_fn(Image.open(image_path).convert('RGB'))
            for image_path in input_images
        ]
        model_input = torch.stack(images)
        return model_input

    def predict(self, model_input):
        model_input = model_input.to(self.device)
        
        with torch.no_grad():
            image_features = self.model.encode_image(model_input)
            image_features /= image_features.norm(dim=-1, keepdim=True)

            # Cosine similarity
            logits = 100.0 * image_features @ self.text_features.T
            
        return logits

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output, dim=1)
        return probabilities.tolist()
