# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_Owlv2ForObjectDetection(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "google/owlv2-large-patch14-finetuned"

        self.processor = AutoImageProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForObjectDetection.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForObjectDetection.from_pretrained(model_id)

        # OWLv2 requires text queries for zero-shot detection.
        # These can be provided in the config, e.g., {"text_queries": [["a photo of a cat", "a photo of a dog"]]}
        self.text_queries = self.config.get("text_queries", [["a photo of a cat", "a photo of a dog"]])
        self.target_sizes = None

    def preprocess(self, input_images):
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        # The model expects a batch of texts, one for each image.
        # We'll replicate the first set of text queries for each image in the batch.
        texts = [self.text_queries[0]] * len(images)
        model_input = self.processor(text=texts, images=images, return_tensors="pt")
        # Store target sizes for postprocessing
        self.target_sizes = torch.tensor([img.size[::-1] for img in images])
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        threshold = self.config.get("threshold", 0.1)
        results = self.processor.post_process_object_detection(outputs=model_output, threshold=threshold, target_sizes=self.target_sizes)

        # The output format requires a list per image in the batch.
        # We process the first (and likely only) image's results.
        result = results[0]
        scores = result["scores"].tolist()
        labels = result["labels"].tolist()
        boxes = result["boxes"].tolist()

        return [scores], [labels], [boxes]
