# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, AutoModelForZeroShotImageClassification
from PIL import Image
import torch

class PyTorch_Transformers_SigLIP2_Large_Patch16_384(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        # For zero-shot classification, candidate labels are required.
        # They must be passed via the config dictionary during initialization.
        self.candidate_labels = self.config.pop("candidate_labels", [])
        if not self.candidate_labels or not isinstance(self.candidate_labels, list):
            features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
            self.candidate_labels = self.features_download(features_file_url)

        model_id = "google/siglip2-large-patch16-384"
        self.processor = AutoProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            # Disabled device_map="auto" to prevent splitting issues
            self.model = AutoModelForZeroShotImageClassification.from_pretrained(model_id, torch_dtype="auto")
            self.model.to(device)
        else:
            self.model = AutoModelForZeroShotImageClassification.from_pretrained(model_id)
            self.model.to(device)

        self.device = device
        self.model.eval()

    def to(self, device, multi_gpu=False):
        self.model.to(device)
        self.device = device

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]

        model_input = self.processor(
            text=self.candidate_labels,
            images=processed_images,
            return_tensors="pt",
            padding=True
        )
        return model_input

    def predict(self, model_input):
        model_input = {k: v.to(self.device) for k, v in model_input.items()}
        with torch.no_grad():
            model_output = self.model(**model_input)
        return model_output

    def postprocess(self, model_output):
        # The model output contains logits_per_image, which represent the similarity scores
        # between each image and each candidate label.
        # We apply softmax to convert these scores into probabilities.
        probabilities = torch.nn.functional.softmax(model_output.logits_per_image, dim=1)
        return probabilities.tolist()
