# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from PIL import Image
import timm

class PyTorch_Timm_MobileNetV3_Large_Minimal_100(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False) # Note: timm models don't use device_map

        model_id = 'timm/tf_mobilenetv3_large_minimal_100.in1k'
        self.model = timm.create_model(model_id, pretrained=True)
        self.model.to(device)
        self.model.eval()

        # Get model-specific transforms from timm
        data_config = timm.data.resolve_model_data_config(self.model)
        self.transforms = timm.data.create_transform(**data_config, is_training=False)

        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)

    def preprocess(self, input_images):
        processed_images = []
        for image_path in input_images:
            img = Image.open(image_path).convert('RGB')
            processed_img = self.transforms(img)
            processed_images.append(processed_img)

        model_input = torch.stack(processed_images)
        return model_input

    def predict(self, model_input):
        return self.model(model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output, dim=1)
        return probabilities.tolist()
