# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
import torch
from diffusers import StableDiffusionXLImg2ImgPipeline
from PIL import Image
import numpy as np

class PyTorch_Diffusers_SDXL_Refiner_Img2Img(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "optimum-intel-internal-testing/tiny-random-stable-diffusion-xl-refiner"
        
        # SDXL models benefit from float16 precision
        self.pipeline = StableDiffusionXLImg2ImgPipeline.from_pretrained(
            model_id,
            torch_dtype=torch.float16,
            variant="fp16",
            use_safetensors=True
        )

    def preprocess(self, input_images_and_prompts):
        images = []
        prompts = []
        for img_path, prompt in input_images_and_prompts:
            images.append(Image.open(img_path).convert('RGB'))
            prompts.append(prompt)
        
        # The pipeline expects 'image' and 'prompt' arguments
        return {"image": images, "prompt": prompts}

    def predict(self, model_input):
        # The pipeline returns an object with an 'images' attribute containing a list of PIL Images
        return self.pipeline(**model_input).images

    def postprocess(self, model_output):
        # The output from the predict step is a list of PIL Image objects.
        # Convert them to a JSON-serializable format (list of lists).
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        # Diffusers pipelines manage their own state, so this can be a no-op
        pass

