# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, AutoModel
from PIL import Image
import torch

class PyTorch_Transformers_Siglip_Large_Patch16_256(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "google/siglip-large-patch16-256"
        self.processor = AutoProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = AutoModel.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModel.from_pretrained(model_id)

        self.model.eval()

        # SigLIP is a zero-shot classifier, so it needs text labels to compare against.
        # We will use ImageNet labels as a default set.
        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)
        self.text_prompts = [f"a photo of a {label}" for label in self.features]

    def preprocess(self, input_images):
        pil_images = [Image.open(image_path).convert('RGB') for image_path in input_images]
        # The processor handles resizing, normalization, and tokenization.
        model_input = self.processor(text=self.text_prompts, images=pil_images, padding="max_length", return_tensors="pt")
        return model_input

    def predict(self, model_input):
        # The model takes both image and text inputs to produce similarity logits.
        with torch.no_grad():
            model_output = self.model(**model_input)
        return model_output

    def postprocess(self, model_output):
        # SigLIP uses a sigmoid function on the logits, not softmax.
        # This gives the probability of each text prompt being a match for the image, independently.
        logits_per_image = model_output.logits_per_image
        probabilities = torch.sigmoid(logits_per_image)
        return probabilities.tolist()
