# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, MagnetForCausalLM
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_AudioMagnet_Small(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "facebook/audio-magnet-small"
        self.processor = AutoProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = MagnetForCausalLM.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = MagnetForCausalLM.from_pretrained(model_id)

        self.max_new_tokens = self.config.get('max_new_tokens', 256)

        self.features = {"sampling_rate": self.model.config.sampling_rate}

    def preprocess(self, input_texts):
        return self.processor(text=input_texts, return_tensors="pt", padding=True)

    def predict(self, model_input):
        return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        return model_output.cpu().numpy().squeeze(axis=1).tolist()
