# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import WhisperForConditionalGeneration, WhisperProcessor
import librosa

class PyTorch_Systran_Faster_Whisper_Large_V2(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        # The provided model 'Systran/faster-whisper-large-v2' is a CTranslate2 conversion.
        # To create a working PyTorch model, we use the original 'openai/whisper-large-v2' model.
        model_id = "openai/whisper-large-v2"

        self.processor = WhisperProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = WhisperForConditionalGeneration.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = WhisperForConditionalGeneration.from_pretrained(model_id)

        self.sampling_rate = self.config.get('sampling_rate', 16_000)

    def preprocess(self, input_audios):
        for i in range(len(input_audios)):
            input_audios[i], _ = librosa.load(input_audios[i], sr=self.sampling_rate)
        model_input = self.processor(input_audios, sampling_rate=self.sampling_rate, return_tensors="pt").input_features
        return model_input

    def predict(self, model_input):
        return self.model.generate(model_input)

    def postprocess(self, model_output):
        return self.processor.batch_decode(model_output, skip_special_tokens=True)
