# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import warnings
import torch
from transformers import LlavaNextProcessor, LlavaNextForConditionalGeneration
from PIL import Image
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_BAAI_Aquila_VL_2B_llava_qwen(PyTorchAbstractClass):
    def __init__(self, config=None):
        warnings.warn("Currently, this model may not support batched forward with multiple images of different sizes.")
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "BAAI/Aquila-VL-2B-llava-qwen"
        self.processor = LlavaNextProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = LlavaNextForConditionalGeneration.from_pretrained(model_id, device_map="auto", torch_dtype=torch.float16)
        else:
            self.model = LlavaNextForConditionalGeneration.from_pretrained(model_id, torch_dtype=torch.float16)

        self.processor.tokenizer.pad_token = self.processor.tokenizer.eos_token

        self.max_new_tokens = self.config.get('max_new_tokens', 100)

    def preprocess(self, input_image_and_questions):
        images = [Image.open(item[0]).convert('RGB') for item in input_image_and_questions]
        questions = [item[1] for item in input_image_and_questions]
        prompts = [f"<|im_start|>user\n<image>\n{q}<|im_end|>\n<|im_start|>assistant\n" for q in questions]
        return self.processor(text=prompts, images=images, return_tensors="pt", padding=True)

    def predict(self, model_input):
        return self.model.generate(**model_input, pad_token_id=self.processor.tokenizer.eos_token_id, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        decoded_outputs = self.processor.batch_decode(model_output, skip_special_tokens=True)
        return [output.split('assistant\n')[-1].strip() for output in decoded_outputs]
