# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoModel, AutoTokenizer
import torch

class PyTorch_Transformers_DeepSeek_OCR(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = 'deepseek-ai/DeepSeek-OCR'
        self.tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

        model_kwargs = {
            "trust_remote_code": True,
            "use_safetensors": True,
            "torch_dtype": torch.bfloat16
        }

        if multi_gpu and device == "cuda":
            self.model = AutoModel.from_pretrained(model_id, device_map="auto", **model_kwargs)
        else:
            self.model = AutoModel.from_pretrained(model_id, **model_kwargs)

        self.model = self.model.eval()

        self.base_size = self.config.get('base_size', 1024)
        self.image_size = self.config.get('image_size', 640)
        self.crop_mode = self.config.get('crop_mode', True)

    def preprocess(self, input_image_and_questions):
        model_inputs = []
        for image_path, question in input_image_and_questions:
            prompt = f"<image>\n{question}"
            model_inputs.append({"prompt": prompt, "image_file": image_path})
        return model_inputs

    def predict(self, model_input):
        results = []
        for single_input in model_input:
            res = self.model.infer(
                self.tokenizer,
                prompt=single_input["prompt"],
                image_file=single_input["image_file"],
                base_size=self.base_size,
                image_size=self.image_size,
                crop_mode=self.crop_mode,
                save_results=False
            )
            results.append(res)
        return results

    def postprocess(self, model_output):
        return model_output
