# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
import torch
from diffusers import ControlNetModel, StableDiffusionControlNetPipeline, UniPCMultistepScheduler
from PIL import Image
import numpy as np

class PyTorch_Diffusers_ControlNet_IP2P(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        # multi_gpu is not directly used for pipelines but kept for consistency
        multi_gpu = self.config.pop("_multi_gpu", False)

        controlnet_model_id = "lllyasviel/control_v11e_sd15_ip2p"
        sd_model_id = "runwayml/stable-diffusion-v1-5"

        # Use float16 for performance on CUDA, as suggested in the model card
        torch_dtype = torch.float16 if device == "cuda" else torch.float32

        controlnet = ControlNetModel.from_pretrained(controlnet_model_id, torch_dtype=torch_dtype)
        self.pipeline = StableDiffusionControlNetPipeline.from_pretrained(
            sd_model_id,
            controlnet=controlnet,
            torch_dtype=torch_dtype
        )
        self.pipeline.scheduler = UniPCMultistepScheduler.from_config(self.pipeline.scheduler.config)
        
        self.seed = self.config.get('seed', 0)
        self.generator = None # Will be initialized in the to() method

    def preprocess(self, input_images_and_prompts):
        images = []
        prompts = []
        for img_path, prompt in input_images_and_prompts:
            images.append(Image.open(img_path).convert('RGB'))
            prompts.append(prompt)
        # The pipeline expects a single image or a list for the 'image' argument
        return {"image": images, "prompt": prompts}

    def predict(self, model_input):
        # num_inference_steps can be a configurable parameter
        num_inference_steps = self.config.get("num_inference_steps", 30)
        return self.pipeline(**model_input, num_inference_steps=num_inference_steps, generator=self.generator).images

    def postprocess(self, model_output):
        # The pipeline output is a list of PIL images
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(self.device)
        self.generator = torch.Generator(device=self.device).manual_seed(self.seed)

    def eval(self):
        # Pipelines are generally in eval mode by default
        pass

