# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoModelForCausalLM, AutoTokenizer
from PIL import Image
import torch

class PyTorch_Transformers_VLM2Vec_Qwen2VL_Image_Captioning(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        # The underlying model architecture (Qwen2-VL) requires trust_remote_code=True
        # and performs best with bfloat16
        model_dtype = torch.bfloat16

        self.tokenizer = AutoTokenizer.from_pretrained("VLM2Vec/VLM2Vec-V2.0", trust_remote_code=True)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForCausalLM.from_pretrained(
                "VLM2Vec/VLM2Vec-V2.0",
                torch_dtype=model_dtype,
                device_map="auto",
                trust_remote_code=True
            )
        else:
            self.model = AutoModelForCausalLM.from_pretrained(
                "VLM2Vec/VLM2Vec-V2.0",
                torch_dtype=model_dtype,
                trust_remote_code=True
            )

        self.max_new_tokens = self.config.get('max_new_tokens', 128)
        self.prompt = self.config.get('prompt', "Describe the image.")

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]

        # Create the prompt structure for the Qwen-VL model
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image"},
                    {"type": "text", "text": self.prompt}
                ]
            }
        ]
        text_prompt = self.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

        # Create a batch of prompts, one for each image
        prompts = [text_prompt] * len(images)

        # Tokenize the text and process the images together
        model_inputs = self.tokenizer(prompts, images=images, return_tensors="pt", padding=True)
        return model_inputs

    def predict(self, model_input):
        # The model_input is a dictionary containing input_ids, attention_mask, and pixel_values.
        # Unpacking the dictionary is a clean way to pass all necessary arguments to the generate method.
        return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        # Decode the full generated sequence, which includes the original prompt.
        full_decoded_preds = self.tokenizer.batch_decode(model_output, skip_special_tokens=True)

        # Heuristically remove the prompt from the beginning of the generated text.
        cleaned_preds = []
        for pred in full_decoded_preds:
            # The chat template adds roles and formatting, so we find the last occurrence of our prompt text.
            prompt_index = pred.rfind(self.prompt)
            if prompt_index != -1:
                # Extract the text that comes after the prompt.
                caption = pred[prompt_index + len(self.prompt):].strip()
                cleaned_preds.append(caption)
            else:
                # If the prompt isn't found (which is unexpected), return the full decoded string.
                cleaned_preds.append(pred.strip())

        return cleaned_preds
