# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_HuggingPanda_docling_layout(PyTorchAbstractClass):
    def __init__(self):
        super().__init__(config)
        self.model_id = "HuggingPanda/docling-layout"
        self.processor = AutoImageProcessor.from_pretrained(self.model_id)
        self.load_hf_model(AutoModelForObjectDetection, self.model_id)

    def preprocess(self, input_images):
        images = [Image.open(path).convert("RGB") for path in input_images]
        self.target_sizes = torch.tensor([img.size[::-1] for img in images])
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        results = self.processor.post_process_object_detection(model_output, threshold=0.3, target_sizes=self.target_sizes)
        result = results[0]
        scores = result["scores"].tolist()
        labels = result["labels"].tolist()
        boxes = result["boxes"].tolist()
        return [scores], [labels], [boxes]
