# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoProcessor, Qwen2VlForConditionalGeneration
from PIL import Image
import torch

class PyTorch_Transformers_Qwen2_VL_Image_Captioning(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "Singh8898/DiegoCropper"

        self.processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

        if multi_gpu and device == "cuda":
            self.model = Qwen2VlForConditionalGeneration.from_pretrained(
                model_id,
                device_map="auto",
                torch_dtype="auto",
                trust_remote_code=True
            )
        else:
            self.model = Qwen2VlForConditionalGeneration.from_pretrained(
                model_id,
                trust_remote_code=True
            )

        self.max_new_tokens = self.config.get('max_new_tokens', 512)

    def preprocess(self, input_images):
        pil_images = [Image.open(p).convert("RGB") for p in input_images]
        # Qwen2-VL is an instruction-tuned model, so it requires a text prompt.
        prompt = "Generate a short caption for this image."
        prompts = [prompt] * len(pil_images)

        model_input = self.processor(text=prompts, images=pil_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        # The preprocessor returns a dictionary of arguments
        return self.model.generate(**model_input, max_new_tokens=self.max_new_tokens)

    def postprocess(self, model_output):
        raw_preds = self.processor.batch_decode(model_output, skip_special_tokens=True)
        
        # The model is instruction-tuned and its output includes the prompt.
        # We need to parse the actual response, which comes after the 'assistant' marker.
        final_preds = []
        for pred in raw_preds:
            parts = pred.split('assistant\n')
            if len(parts) > 1:
                # Take the last part and strip any leading/trailing whitespace
                final_preds.append(parts[-1].strip())
            else:
                # Fallback in case the output format is unexpected
                final_preds.append(pred.strip())
        return final_preds
