# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, AutoModel
from PIL import Image
import torch

class PyTorch_Transformers_SigLIP2_SO400M_Patch16_384(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "google/siglip2-so400m-patch16-384"

        self.processor = AutoProcessor.from_pretrained(model_id)
        self.model = self.load_hf_model(AutoModel, model_id)
        self.model.eval()

        # For zero-shot classification, we use ImageNet classes as the default text labels
        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)

        # Pre-process the text labels once during initialization for efficiency
        self.text_inputs = self.processor(text=self.features, padding=True, return_tensors="pt")

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        # The processor handles resizing, normalization, etc.
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        # This is a zero-shot model, so we need to provide both image and text inputs.
        # The text inputs (from self.features) were pre-processed in __init__.
        # We just need to ensure they are on the same device as the image inputs.
        device = model_input['pixel_values'].device
        text_inputs = {k: v.to(device) for k, v in self.text_inputs.items()}

        with torch.no_grad():
            outputs = self.model(
                pixel_values=model_input['pixel_values'],
                input_ids=text_inputs['input_ids'],
                attention_mask=text_inputs['attention_mask']
            )
        
        # The model output contains logits representing the similarity between each image and each text label.
        return outputs.logits_per_image

    def postprocess(self, model_output):
        # The model output (logits_per_image) can be converted to probabilities using softmax.
        probabilities = torch.nn.functional.softmax(model_output, dim=1)
        return probabilities.tolist()
