# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_TableTransformerStructureRecognition(PyTorchAbstractClass):
    def __init__(self):
        super().__init__(config)
        model_id = 'microsoft/table-transformer-structure-recognition-v1.1-pub'
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        self.model = self.load_hf_model(AutoModelForObjectDetection, model_id)

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]
        self.original_image_sizes = [img.size for img in images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor([size[::-1] for size in self.original_image_sizes])
        results = self.processor.post_process_object_detection(model_output, threshold=0.5, target_sizes=target_sizes)
        scores = results[0]['scores'].tolist()
        labels = results[0]['labels'].tolist()
        boxes = results[0]['boxes'].tolist()
        return [scores], [labels], [boxes]
