# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch
import warnings

class PyTorch_Transformers_cmarkea_detr_layout_detection(PyTorchAbstractClass):
    def __init__(self):
        super().__init__(config)
        warnings.warn("The batch size should be 1.")
        self.processor = AutoImageProcessor.from_pretrained("cmarkea/detr-layout-detection")
        self.load_hf_model(AutoModelForObjectDetection, "cmarkea/detr-layout-detection")

    def preprocess(self, input_images):
        images = [Image.open(img_path).convert("RGB") for img_path in input_images]
        self.original_sizes = [img.size[::-1] for img in images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor(self.original_sizes)
        results = self.processor.post_process_object_detection(model_output, threshold=0.5, target_sizes=target_sizes)[0]
        scores = results["scores"].tolist()
        labels = results["labels"].tolist()
        boxes = results["boxes"].tolist()
        return [scores], [labels], [boxes]
