# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusionXLPipeline

class PyTorch_Diffusers_Juggernaut_XL_V9(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        if multi_gpu and device == "cuda":
            self.pipeline = StableDiffusionXLPipeline.from_pretrained("stablediffusionapi/juggernaut-xl-v9", torch_dtype=torch.float16, use_safetensors=True, variant="fp16")
        else:
            self.pipeline = StableDiffusionXLPipeline.from_pretrained("stablediffusionapi/juggernaut-xl-v9", use_safetensors=True)
        self.num_inference_steps = self.config.get('num_inference_steps', 30)

    def preprocess(self, input_prompts):
        return input_prompts

    def predict(self, model_input):
        return self.pipeline(model_input, num_inference_steps=self.num_inference_steps).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
