# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusionXLInpaintPipeline
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_DiffusionLight_TurboLoRA(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        base_model_id = "stabilityai/stable-diffusion-xl-base-1.0"
        lora_model_id = "DiffusionLight/TurboLoRA"

        self.pipeline = StableDiffusionXLInpaintPipeline.from_pretrained(
            base_model_id,
            torch_dtype=torch.float16,
            variant="fp16",
            use_safetensors=True
        )
        self.pipeline.load_lora_weights(lora_model_id)
        self.seed = self.config.get('seed', 0)

    def preprocess(self, input_images_masks_and_prompts):
        images = []
        masks = []
        prompts = []
        for img_path, mask_path, prompt in input_images_masks_and_prompts:
            images.append(Image.open(img_path).convert('RGB'))
            masks.append(Image.open(mask_path).convert('RGB'))
            prompts.append(prompt)
        return {"image": images, "mask_image": masks, "prompt": prompts}

    def predict(self, model_input):
        generator = torch.Generator(device=self.device).manual_seed(self.seed)
        return self.pipeline(**model_input, generator=generator).images

    def postprocess(self, model_output):
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
