# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, BarkModel

class PyTorch_Transformers_Marvis_TTS_100m_v0_2(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        self.processor = AutoProcessor.from_pretrained("Marvis-AI/marvis-tts-100m-v0.2")
        self.model = BarkModel.from_pretrained("Marvis-AI/marvis-tts-100m-v0.2")
        self.model.to(device)

        self.features = {"sampling_rate": self.model.generation_config.sample_rate}

    def preprocess(self, input_texts):
        return self.processor(text=input_texts, return_tensors="pt")

    def predict(self, model_input):
        return self.model.generate(**model_input)

    def postprocess(self, model_output):
        return model_output.cpu().numpy().tolist()
