# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_RTDetr_R50VD_COCO_O365(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        self.device = torch.device(device)

        model_id = "PekingU/rtdetr_r50vd_coco_o365"

        self.processor = AutoImageProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = AutoModelForObjectDetection.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForObjectDetection.from_pretrained(model_id).to(self.device)
        
        self.model.eval()

    def preprocess(self, input_images):
        pil_images = [Image.open(path).convert('RGB') for path in input_images]
        self.target_sizes = torch.tensor([img.size[::-1] for img in pil_images])
        model_input = self.processor(images=pil_images, return_tensors="pt").to(self.device)
        return model_input

    def predict(self, model_input):
        with torch.no_grad():
            return self.model(**model_input)

    def postprocess(self, model_output):
        results = self.processor.post_process_object_detection(
            model_output, 
            target_sizes=self.target_sizes.to(self.device),
            threshold=0.3
        )
        
        # Assuming batch size is 1
        result = results[0]
        scores = result["scores"].tolist()
        labels = result["labels"].tolist()
        boxes = result["boxes"].tolist()

        return [scores], [labels], [boxes]
