# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import WhisperForConditionalGeneration, WhisperProcessor
import librosa

class PyTorch_Transformers_BanglaASR(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "bangla-speech-processing/BanglaASR"
        self.processor = WhisperProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = WhisperForConditionalGeneration.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = WhisperForConditionalGeneration.from_pretrained(model_id)

        self.sampling_rate = self.config.get('sampling_rate', 16_000)

    def preprocess(self, input_audios):
        audios = []
        for audio_path in input_audios:
            audio, _ = librosa.load(audio_path, sr=self.sampling_rate)
            audios.append(audio)
        
        model_input = self.processor(audios, sampling_rate=self.sampling_rate, return_tensors="pt").input_features
        return model_input

    def predict(self, model_input):
        return self.model.generate(model_input)

    def postprocess(self, model_output):
        return self.processor.batch_decode(model_output, skip_special_tokens=True)
