# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

class PyTorch_Transformers_Orpheus_3B_0_1_FT(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "unsloth/orpheus-3b-0.1-ft"
        self.processor = AutoTokenizer.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", torch_dtype=torch.bfloat16)
        else:
            self.model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16)

        self.max_new_tokens = self.config.get('max_new_tokens', 2048)

        # Orpheus models have a fixed sampling rate of 24000
        self.features = {"sampling_rate": 24000}

    def preprocess(self, input_texts):
        return self.processor(text=input_texts, return_tensors="pt", padding=True)

    def predict(self, model_input):
        input_length = model_input['input_ids'].shape[1]
        # The model generates a sequence of tokens including the prompt and the audio representation.
        output = self.model.generate(**model_input, max_new_tokens=self.max_new_tokens, do_sample=False)
        # We slice the output tensor to remove the prompt tokens, leaving only the generated audio tokens.
        return output[:, input_length:]

    def postprocess(self, model_output):
        # The output tokens represent the audio waveform, which we convert to a float numpy array and then to a list.
        return model_output.cpu().to(torch.float32).numpy().tolist()
