# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_DetrResnet50FinetunedCppe5(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "qubvel-hf/detr-resnet-50-finetuned-10k-cppe5"

        self.processor = AutoImageProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForObjectDetection.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForObjectDetection.from_pretrained(model_id)
        
        # To pass original image sizes to postprocess
        self.original_sizes = []

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]
        self.original_sizes = [img.size for img in images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor([size[::-1] for size in self.original_sizes])
        results = self.processor.post_process_object_detection(outputs=model_output, threshold=0.5, target_sizes=target_sizes)
        
        # Assuming batch size is 1
        result = results[0]
        scores = result["scores"].tolist()
        labels = result["labels"].tolist()
        boxes = result["boxes"].tolist()
        
        return [scores], [labels], [boxes]
