# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import FluxKontextPipeline
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_FluxKontext(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False) # Not directly used by pipeline, but good practice to have

        # The provided model ID 'unsloth/FLUX.1-Kontext-dev-GGUF' is for GGUF format,
        # which is not directly compatible with diffusers. Using the base model from the example code.
        model_id = "black-forest-labs/FLUX.1-Kontext-dev"
        
        self.pipeline = FluxKontextPipeline.from_pretrained(
            model_id,
            torch_dtype=torch.bfloat16
        )

    def preprocess(self, input_images_and_prompts):
        images = []
        prompts = []
        for img_path, prompt in input_images_and_prompts:
            images.append(Image.open(img_path).convert('RGB'))
            prompts.append(prompt)
        
        # The pipeline expects a single image or a batch of images for the 'image' key.
        # It also accepts a single prompt or a list of prompts.
        return {"image": images, "prompt": prompts}

    def predict(self, model_input):
        # The pipeline call includes default parameters from the model card example
        return self.pipeline(**model_input, guidance_scale=2.5).images

    def postprocess(self, model_output):
        # The pipeline output is a list of PIL images.
        # Convert them to a list of numpy arrays in list format.
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.pipeline.to(device)

    def eval(self):
        # Pipelines manage their components' modes, so a top-level eval is often not needed.
        # This method is here for API consistency.
        pass

