# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoImageProcessor, TimesformerForVideoClassification
import av
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Transformers_Timesformer_Base_Finetuned_K400(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "facebook/timesformer-base-finetuned-k400"
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = TimesformerForVideoClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = TimesformerForVideoClassification.from_pretrained(model_id)

        self.features = [v for k, v in sorted(self.model.config.id2label.items())]

    def preprocess(self, input_videos):
        container = av.open(input_videos[0])
        # The model was trained on 8 frames.
        indices = self.sample_frame_indices(clip_len=8, frame_sample_rate=1, seg_len=container.streams.video[0].frames)
        video = self.read_video_pyav(container, indices)
        inputs = self.processor(videos=list(video), return_tensors="pt")
        return inputs

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
