# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusionPipeline, AutoencoderKL

class PyTorch_Diffusers_Realistic_Vision_V5_1(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        vae_model_id = "stabilityai/sd-vae-ft-mse-original"
        model_id = "SG161222/Realistic_Vision_V5.1_noVAE"

        if multi_gpu and device == "cuda":
            vae = AutoencoderKL.from_pretrained(vae_model_id, torch_dtype=torch.float16)
            self.pipeline = StableDiffusionPipeline.from_pretrained(model_id, vae=vae, torch_dtype=torch.float16)
        else:
            vae = AutoencoderKL.from_pretrained(vae_model_id)
            self.pipeline = StableDiffusionPipeline.from_pretrained(model_id, vae=vae)
        
        self.num_inference_steps = self.config.get('num_inference_steps', 50)

    def preprocess(self, input_prompts):
        return input_prompts

    def predict(self, model_input):
        return self.pipeline(model_input, num_inference_steps=self.num_inference_steps).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
