# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, AutoModel
from PIL import Image
import torch

class PyTorch_Transformers_Siglip_Base_Patch16_224(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "google/siglip-base-patch16-224"
        self.processor = AutoProcessor.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            # Disabled device_map="auto" to prevent splitting issues
            self.model = AutoModel.from_pretrained(model_id, torch_dtype="auto")
            self.model.to(device)
        else:
            self.model = AutoModel.from_pretrained(model_id)
            self.model.to(device)

        self.device = device
        self.model.eval()

        self.candidate_labels = self.config.get("candidate_labels", [])
        if not self.candidate_labels or not isinstance(self.candidate_labels, list):
            features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
            self.candidate_labels = self.features_download(features_file_url)

    def to(self, device, multi_gpu=False):
        self.model.to(device)
        self.device = device

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]

        model_input = self.processor(
            text=self.candidate_labels,
            images=processed_images,
            padding="max_length",
            return_tensors="pt"
        )
        return model_input

    def predict(self, model_input):
        model_input = {k: v.to(self.device) for k, v in model_input.items()}
        with torch.no_grad():
            model_output = self.model(**model_input)
        return model_output

    def postprocess(self, model_output):
        logits_per_image = model_output.logits_per_image
        probabilities = torch.sigmoid(logits_per_image)
        return probabilities.tolist()
