# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
import torch
from transformers import AutoVideoProcessor, AutoModelForVideoClassification
import av
import numpy as np

class PyTorch_Transformers_Vjepa2_Vitl_Fpc32_256_Diving48(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "facebook/vjepa2-vitl-fpc32-256-diving48"
        self.processor = AutoVideoProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForVideoClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForVideoClassification.from_pretrained(model_id)

        self.features = [v for k, v in sorted(self.model.config.id2label.items())]

    def preprocess(self, input_videos):
        container = av.open(input_videos[0])
        # sample frames. The model expects 32 frames.
        indices = self.sample_frame_indices(clip_len=self.model.config.num_frames, frame_sample_rate=1, seg_len=container.streams.video[0].frames)
        video = self.read_video_pyav(container, indices)
        
        # process with processor
        inputs = self.processor(videos=list(video), return_tensors="pt")
        return inputs.pixel_values

    def predict(self, model_input):
        return self.model(pixel_values=model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
