# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModel
from PIL import Image
import torch

class PyTorch_Transformers_Clip_ViT_B_32_Vision(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "Qdrant/clip-ViT-B-32-vision"
        
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        self.model = self.load_hf_model(AutoModel, model_id)
        self.model.eval()

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        # This model outputs embeddings, not classification logits.
        # We extract the pooler_output which corresponds to the [CLS] token embedding.
        embeddings = model_output.pooler_output
        return embeddings.tolist()
