# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModel
from PIL import Image
import torch

class PyTorch_Transformers_Clip_ViT_B_32_Vision(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        
        # The requested model 'Qdrant/clip-ViT-B-32-vision' is an ONNX model.
        # We are using the original PyTorch model 'openai/clip-vit-base-patch32' which it is based on.
        model_id = "openai/clip-vit-base-patch32"
        self.processor = AutoImageProcessor.from_pretrained(model_id)
        
        if multi_gpu and device == "cuda":
            self.model = AutoModel.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModel.from_pretrained(model_id)
            self.model.eval()

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        # This model is a vision encoder that outputs image embeddings, not classification logits.
        # We return the pooled output which represents the image feature vector.
        embeddings = model_output.pooler_output
        return embeddings.tolist()
