# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from PIL import Image
import warnings
from ultralytics import YOLO
from huggingface_hub import hf_hub_download

class PyTorch_Ultralytics_Anzhcs_YOLOs(PyTorchAbstractClass):
    def __init__(self):
        warnings.warn("The batch size should be 1.")
        # This repository contains multiple models. We are selecting 'Anzhc HeadHair seg y8m.pt' as a representative example.
        model_path = hf_hub_download(repo_id="Anzhc/Anzhcs_YOLOs", filename="Anzhc HeadHair seg y8m.pt")
        self.model = YOLO(model_path)

    def preprocess(self, input_images):
        # The ultralytics YOLO model handles preprocessing internally when given a PIL image.
        model_input = [Image.open(img_path).convert('RGB') for img_path in input_images]
        return model_input

    def predict(self, model_input):
        # The model returns a list of ultralytics Results objects.
        return self.model(model_input)

    def postprocess(self, model_output):
        # The output is a list of ultralytics.engine.results.Results objects.
        # We process the first result as batch size is assumed to be 1.
        results = model_output[0]
        scores = results.boxes.conf.tolist()
        labels = results.boxes.cls.tolist()
        boxes = results.boxes.xyxy.tolist()
        return [scores], [labels], [boxes]
