# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import VisionEncoderDecoderModel, AutoImageProcessor, AutoTokenizer
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from PIL import Image

class PyTorch_Transformers_Manga_OCR_Base(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "kha-white/manga-ocr-base"

        self.image_processor = AutoImageProcessor.from_pretrained(model_id)
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)

        if multi_gpu and device == "cuda":
            self.model = VisionEncoderDecoderModel.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = VisionEncoderDecoderModel.from_pretrained(model_id)

        # From model's config.json, max_length is 50, which is more suitable for OCR than the default 16.
        self.max_length = self.config.get('max_length', 50)
        self.num_beams = self.config.get('num_beams', 4)

    def preprocess(self, input_images):
        images = []
        for image_path in input_images:
            image = Image.open(image_path).convert('RGB')
            images.append(image)

        pixel_values = self.image_processor(images=images, return_tensors="pt").pixel_values
        return pixel_values

    def predict(self, model_input):
        return self.model.generate(model_input, max_length=self.max_length, num_beams=self.num_beams)

    def postprocess(self, model_output):
        preds = self.tokenizer.batch_decode(model_output, skip_special_tokens=True)
        return [pred.strip() for pred in preds]
