# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoProcessor, AutoModelForZeroShotImageClassification
from PIL import Image
import torch

class PyTorch_Transformers_SigLIP2_SO400M_Patch16_NAFlex(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "google/siglip2-so400m-patch16-naflex"
        
        self.processor = AutoProcessor.from_pretrained(model_id)
        self.model = self.load_hf_model(AutoModelForZeroShotImageClassification, model_id)
        self.model.eval()

    def preprocess(self, input_images):
        processed_images = [
            Image.open(image_path).convert('RGB')
            for image_path in input_images
        ]
        model_input = self.processor(images=processed_images, return_tensors="pt")
        return model_input

    def predict(self, model_input, **kwargs):
        candidate_labels = kwargs.get("candidate_labels")
        if not candidate_labels or not isinstance(candidate_labels, list):
            raise ValueError("A list of candidate_labels must be provided via kwargs for zero-shot classification.")

        # Process text labels
        text_inputs = self.processor(text=candidate_labels, return_tensors="pt", padding=True)

        # Move all tensors to the correct device
        pixel_values = model_input.pixel_values.to(self.device)
        input_ids = text_inputs.input_ids.to(self.device)
        attention_mask = text_inputs.attention_mask.to(self.device)

        with torch.no_grad():
            outputs = self.model(pixel_values=pixel_values, input_ids=input_ids, attention_mask=attention_mask)

        return outputs

    def postprocess(self, model_output):
        # The model output contains logits per image, which we can convert to probabilities
        probabilities = torch.nn.functional.softmax(model_output.logits_per_image, dim=1)
        return probabilities.tolist()
