# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoImageProcessor, AutoModelForDepthEstimation
from PIL import Image
import numpy as np

class PyTorch_Transformers_InternVL2_5_HiMTok_8B(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        self.image_processor = AutoImageProcessor.from_pretrained("yayafengzi/InternVL2_5-HiMTok-8B")
        
        if multi_gpu and device == "cuda":
            self.model = AutoModelForDepthEstimation.from_pretrained("yayafengzi/InternVL2_5-HiMTok-8B", device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForDepthEstimation.from_pretrained("yayafengzi/InternVL2_5-HiMTok-8B")

        self.original_sizes = None

    def preprocess(self, input_images):
        images = [Image.open(input_image) for input_image in input_images]
        self.original_sizes = [image.size for image in images]
        return self.image_processor(images, return_tensors="pt")

    def predict(self, model_input):
        return self.model(**model_input).predicted_depth

    def postprocess(self, model_output):
        predictions_resized = []
        for output, original_size in zip(model_output, self.original_sizes):
            # Interpolate to original size
            prediction = torch.nn.functional.interpolate(
                output.unsqueeze(0).unsqueeze(0),
                size=original_size[::-1],  # PIL size is (width, height), torch size is (height, width)
                mode="bicubic",
                align_corners=False,
            )
            # Normalize and convert to list
            output = prediction.squeeze().cpu().numpy()
            formatted = (output * 255 / np.max(output)).astype("uint8").tolist()
            predictions_resized.append(formatted)
        self.original_sizes = None
        return predictions_resized
