# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import SpeechT5Processor, SpeechT5ForTextToSpeech, SpeechT5HifiGan
from datasets import load_dataset
import torch

class PyTorch_Transformers_SpeechT5_TTS_Voxpopuli_ES(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False) # Note: SpeechT5 does not use device_map, using .to(device)

        model_id = "kfahn/speecht5_finetuned_voxpopuli_es"
        vocoder_id = "microsoft/speecht5_hifigan"
        embeddings_dataset_id = "Matthijs/cmu-arctic-xvectors"

        self.processor = SpeechT5Processor.from_pretrained(model_id)
        self.model = SpeechT5ForTextToSpeech.from_pretrained(model_id).to(device)
        self.vocoder = SpeechT5HifiGan.from_pretrained(vocoder_id).to(device)

        # Load speaker embeddings
        embeddings_dataset = load_dataset(embeddings_dataset_id, split="validation")
        self.speaker_embeddings = torch.tensor(embeddings_dataset[7306]["xvector"]).unsqueeze(0).to(device)

        self.features = {"sampling_rate": self.vocoder.config.sampling_rate}

    def preprocess(self, input_texts):
        return self.processor(text=input_texts, return_tensors="pt", padding=True)

    def predict(self, model_input):
        input_ids = model_input["input_ids"].to(self.model.device)
        spectrograms = self.model.generate(input_ids=input_ids, speaker_embeddings=self.speaker_embeddings)
        return spectrograms

    def postprocess(self, model_output):
        speech = self.vocoder(model_output)
        return speech.cpu().numpy().tolist()
