# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import SpeechT5Processor, SpeechT5ForTextToSpeech, SpeechT5HifiGan
import torch
from datasets import load_dataset

class PyTorch_Transformers_SpeechT5_TTS_ES(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        self.device = device
        model_id = "kfahn/speecht5_finetuned_voxpopuli_es"

        self.processor = SpeechT5Processor.from_pretrained(model_id)
        self.vocoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan").to(device)

        if multi_gpu and device == "cuda":
            self.model = SpeechT5ForTextToSpeech.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = SpeechT5ForTextToSpeech.from_pretrained(model_id).to(device)

        embeddings_dataset = load_dataset("Matthijs/cmu-arctic-xvectors", split="validation")
        self.speaker_embeddings = torch.tensor(embeddings_dataset[7306]["xvector"]).unsqueeze(0).to(device)

        self.features = {"sampling_rate": self.vocoder.config.sampling_rate}

    def preprocess(self, input_texts):
        inputs = self.processor(text=input_texts, return_tensors="pt", padding=True)
        return {k: v.to(self.device) for k, v in inputs.items()}

    def predict(self, model_input):
        batch_size = model_input["input_ids"].shape[0]
        speaker_embeddings = self.speaker_embeddings.repeat(batch_size, 1)
        spectrogram = self.model.generate_speech(model_input["input_ids"], speaker_embeddings)
        return spectrogram

    def postprocess(self, model_output):
        with torch.no_grad():
            speech = self.vocoder(model_output)
        return speech.cpu().numpy().tolist()
