# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from PIL import Image
import timm

class Timm_MobileNetV3_Small_050_Lamb_In1k(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False) # timm doesn't have a simple multi-gpu loader like transformers

        model_id = "timm/mobilenetv3_small_050.lamb_in1k"
        self.model = timm.create_model(model_id, pretrained=True)
        self.model.to(device)
        self.model.eval()

        # Get model-specific transforms from timm
        data_config = timm.data.resolve_model_data_config(self.model)
        self.preprocessor = timm.data.create_transform(**data_config, is_training=False)

        # Download ImageNet class labels
        features_file_url = "http://s3.amazonaws.com/store.carml.org/synsets/imagenet/synset.txt"
        self.features = self.features_download(features_file_url)

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert('RGB') for image_path in input_images]
        processed_images = [self.preprocessor(img) for img in images]
        model_input = torch.stack(processed_images)
        return model_input

    def predict(self, model_input):
        return self.model(model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output, dim=1)
        return probabilities.tolist()
