# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from transformers import AutoProcessor, VideoMAEForVideoClassification
import av
import numpy as np

class PyTorch_Transformers_XCLIP_Base_Patch16(PyTorchAbstractClass):
    def __init__(self, config=None):
        super().__init__(config)
        model_id = "microsoft/xclip-base-patch16"
        self.processor = AutoProcessor.from_pretrained(model_id)
        self.model = self.load_hf_model(VideoMAEForVideoClassification, model_id)

        self.features = [v for k, v in sorted(self.model.config.text_config['id2label'].items())]

    def preprocess(self, input_videos):
        container = av.open(input_videos[0])
        # sample 8 frames, as specified in the model card
        indices = self.sample_frame_indices(clip_len=8, frame_sample_rate=1, seg_len=container.streams.video[0].frames)
        video = self.read_video_pyav(container, indices)
        pixel_values = self.processor(videos=list(video), return_tensors="pt").pixel_values
        return pixel_values

    def predict(self, model_input):
        return self.model(model_input)

    def postprocess(self, model_output):
        probabilities = torch.nn.functional.softmax(model_output.logits, dim=1)
        return probabilities.tolist()
