# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import VitsTokenizer, VitsModel
import torch

class PyTorch_Transformers_Vits_MMS_TTS_Uig(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "ixxan/mms-tts-uig-script_arabic-UQSpeech"

        self.tokenizer = VitsTokenizer.from_pretrained(model_id)
        self.model = VitsModel.from_pretrained(model_id).to(device)

        self.features = {"sampling_rate": self.model.config.sampling_rate}

    def preprocess(self, input_texts):
        return self.tokenizer(text=input_texts, return_tensors="pt", padding=True)

    def predict(self, model_input):
        model_input = {k: v.to(self.model.device) for k, v in model_input.items()}
        with torch.no_grad():
            output = self.model(**model_input)
        return output.waveform

    def postprocess(self, model_output):
        return model_output.cpu().numpy().tolist()
