# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch
import warnings

class PyTorch_Transformers_YolosSmallSignatureDetection(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)
        model_id = "mdefrance/yolos-small-signature-detection"

        warnings.warn("The batch size should be 1 for this model.")

        self.processor = AutoImageProcessor.from_pretrained(model_id)
        if multi_gpu and device == "cuda":
            self.model = AutoModelForObjectDetection.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForObjectDetection.from_pretrained(model_id)
        
        self.target_sizes = []

    def preprocess(self, input_images):
        images = []
        self.target_sizes = []
        for path in input_images:
            image = Image.open(path).convert("RGB")
            images.append(image)
            self.target_sizes.append(image.size)
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor(self.target_sizes)
        results = self.processor.post_process_object_detection(outputs=model_output, threshold=0.5, target_sizes=target_sizes)[0]
        return [results["scores"].tolist()], [results["labels"].tolist()], [results["boxes"].tolist()]
