# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import StableDiffusion3Pipeline

class PyTorch_Diffusers_StableDiffusion3_Tiny_Random(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "optimum-intel-internal-testing/stable-diffusion-3-tiny-random"
        dtype = torch.float16 if device == "cuda" else torch.float32

        self.pipeline = StableDiffusion3Pipeline.from_pretrained(model_id, torch_dtype=dtype)
        
        self.num_inference_steps = self.config.get('num_inference_steps', 2)
        self.guidance_scale = self.config.get('guidance_scale', 7.0)

    def preprocess(self, input_prompts):
        return input_prompts

    def predict(self, model_input):
        return self.pipeline(
            prompt=model_input,
            num_inference_steps=self.num_inference_steps,
            guidance_scale=self.guidance_scale
        ).images

    def postprocess(self, model_output):
        import numpy as np
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        self.device = device
        self.pipeline.to(device)

    def eval(self):
        pass
