# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass
from transformers import AutoImageProcessor, AutoModelForObjectDetection
from PIL import Image
import torch

class PyTorch_Transformers_DETR_ResNet50(PyTorchAbstractClass):
    def __init__(self):
        super().__init__(config)
        self.processor = AutoImageProcessor.from_pretrained("facebook/detr-resnet-50")
        self.model = self.load_hf_model(AutoModelForObjectDetection, "facebook/detr-resnet-50")

    def preprocess(self, input_images):
        images = [Image.open(image_path).convert("RGB") for image_path in input_images]
        self.image_sizes = [image.size for image in images]
        model_input = self.processor(images=images, return_tensors="pt")
        return model_input

    def predict(self, model_input):
        return self.model(**model_input)

    def postprocess(self, model_output):
        target_sizes = torch.tensor([size[::-1] for size in self.image_sizes])
        results = self.processor.post_process_object_detection(model_output, target_sizes=target_sizes, threshold=0.1)[0]
        scores = results["scores"].tolist()
        labels = results["labels"].tolist()
        boxes = results["boxes"].tolist()
        return [scores], [labels], [boxes]
