# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.nn.functional import softmax

class PyTorch_Transformers_KuBERT_Sentiment(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        model_id = "asosoft/KuBERT-Central-Kurdish-BERT-Model"
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)

        # This is a base model without a classification head. 
        # We load it with AutoModelForSequenceClassification to add a randomly initialized head
        # suitable for fine-tuning on a downstream task like sentiment analysis.
        if multi_gpu and device == "cuda":
            self.model = AutoModelForSequenceClassification.from_pretrained(model_id, device_map="auto", torch_dtype="auto")
        else:
            self.model = AutoModelForSequenceClassification.from_pretrained(model_id)

        # Since the base model has no pre-defined labels, we check for them and
        # create default labels if they don't exist. This makes the model ready for fine-tuning.
        if hasattr(self.model.config, "id2label") and self.model.config.id2label:
            self.features = list(self.model.config.id2label.values())
        else:
            # Defaulting to a binary classification task (e.g., negative/positive)
            self.features = ["LABEL_0", "LABEL_1"]
            self.model.config.id2label = {i: label for i, label in enumerate(self.features)}
            self.model.config.label2id = {label: i for i, label in enumerate(self.features)}

    def preprocess(self, input_texts):
        return self.tokenizer(input_texts, return_tensors="pt", padding=True, truncation=True)

    def predict(self, model_input):
        return self.model(**model_input).logits

    def postprocess(self, model_output):
        return softmax(model_output, dim=1).tolist()
