# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

import torch
from diffusers import AutoPipelineForImage2Image
from PIL import Image
import numpy as np
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

class PyTorch_Diffusers_Relighting_LoRA(PyTorchAbstractClass):
    def __init__(self, config=None):
        self.config = config if config else dict()
        device = self.config.pop("_device", "cpu")
        multi_gpu = self.config.pop("_multi_gpu", False)

        base_model_id = "black-forest-labs/FLUX.1-Kontext-dev"
        lora_model_id = "kontext-community/relighting-kontext-dev-lora-v3"

        # FLUX models are large and perform best with bfloat16
        self.pipeline = AutoPipelineForImage2Image.from_pretrained(
            base_model_id,
            torch_dtype=torch.bfloat16,
            variant="fp16"  # Use fp16 variant for smaller download size
        )
        
        # Load the LoRA adapter for relighting
        self.pipeline.load_lora_weights(lora_model_id)

    def preprocess(self, input_images_and_prompts):
        images = []
        prompts = []
        for img_path, prompt in input_images_and_prompts:
            images.append(Image.open(img_path).convert("RGB"))
            prompts.append(prompt)
        
        # The pipeline expects 'image' and 'prompt' as arguments
        return {"image": images, "prompt": prompts}

    def predict(self, model_input):
        # The pipeline returns an object with an 'images' attribute containing a list of PIL Images
        return self.pipeline(**model_input).images

    def postprocess(self, model_output):
        # The output from predict is a list of PIL Images
        # Convert each PIL Image to a numpy array and then to a list for JSON serialization
        return [np.array(img).tolist() for img in model_output]

    def to(self, device):
        """Move the pipeline to the specified device."""
        self.pipeline.to(device)

    def eval(self):
        """Pipelines do not have a traditional eval mode, but we can disable progress bars for cleaner inference."""
        self.pipeline.set_progress_bar_config(disable=True)
