name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch. Change as needed.

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Pytorch
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/pytorch/Dockerfile.gpu_pytorch2.0.1_cuda11.7
        push: true
        tags: xlabub/pytorch-agent:latest
    - name: Build and push Tensorflow
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/tensorflow/Dockerfile.gpu_tensorflow2.10_cuda11.2
        push: true
        tags: xlabub/tensorflow-agent:latest
    - name: Build and push MXNet
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/mxnet/Dockerfile.cpu_mxnet1.9.1
        push: true
        tags: xlabub/mxnet-agent:latest
