# Generated by automation script
from mlmodelscope.pytorch_agent.models.pytorch_abc import PyTorchAbstractClass

from ultralyticsplus import YOLO
from PIL import Image
import warnings

class PyTorch_Ultralytics_YOLOv8n_HardHat(PyTorchAbstractClass):
    def __init__(self):
        warnings.warn("The batch size should be 1.")
        self.model = YOLO('keremberke/yolov8n-hard-hat-detection')
        self.model.overrides['conf'] = 0.25
        self.model.overrides['iou'] = 0.45
        self.model.overrides['agnostic_nms'] = False
        self.model.overrides['max_det'] = 1000

    def preprocess(self, input_images):
        return input_images

    def predict(self, model_input):
        return self.model.predict(model_input)

    def postprocess(self, model_output):
        results = model_output[0]
        scores = results.boxes.conf.tolist()
        labels = results.boxes.cls.tolist()
        boxes = results.boxes.xyxy.tolist()
        return [scores], [labels], [boxes]
